// Cocktail Database — IBA Standard Recipes + Extended Data
// flavor: {sweet, sour, bitter, strong, fresh, complex} 各0〜5

const COCKTAILS = [
  // ===== ウォッカ =====
  {id:1, name:"Cosmopolitan", nameJa:"コスモポリタン", base:"ウォッカ", taste:"酸味", glass:"カクテルグラス",
   color1:"#e8547a", color2:"#c0384c", abv:26, iba:true, era:"モダン",
   photo:"cosmopolitan cocktail pink",
   flavor:{sweet:2,sour:3,bitter:0,strong:3,fresh:3,complex:2},
   ingredients:[["シトラスウォッカ","40ml"],["コアントロー","15ml"],["フレッシュライムジュース","15ml"],["クランベリージュース","30ml"]],
   method:"シェイク後、冷やしたカクテルグラスに注ぐ。フレイムドオレンジピールを飾る。",
   note:"1990年代ニューヨークで流行。ドラマ「セックス・アンド・ザ・シティ」で世界的に有名に。"},
  {id:2, name:"Espresso Martini", nameJa:"エスプレッソ・マティーニ", base:"ウォッカ", taste:"苦味", glass:"カクテルグラス",
   color1:"#1c0d05", color2:"#3d1f0e", abv:24, iba:false, era:"モダン",
   photo:"espresso martini coffee cocktail",
   flavor:{sweet:3,sour:0,bitter:4,strong:3,fresh:0,complex:3},
   ingredients:[["ウォッカ","50ml"],["コーヒーリキュール","30ml"],["フレッシュエスプレッソ","30ml"],["砂糖シロップ","10ml"]],
   method:"全材料を強くシェイク。冷やしたグラスに注ぎ、コーヒー豆3粒を飾る。",
   note:"1983年ロンドン。バーテンダーのディック・ブラッドセルがモデルのリクエストで考案。"},
  {id:3, name:"Moscow Mule", nameJa:"モスコー・ミュール", base:"ウォッカ", taste:"辛口", glass:"ハイボールグラス",
   color1:"#c8e6c9", color2:"#66bb6a", abv:10, iba:false, era:"クラシック",
   photo:"moscow mule ginger beer cocktail",
   flavor:{sweet:1,sour:2,bitter:0,strong:1,fresh:5,complex:1},
   ingredients:[["ウォッカ","45ml"],["ジンジャービア","120ml"],["フレッシュライムジュース","15ml"]],
   method:"銅製マグカップに氷を入れ、ウォッカとライムを注ぎ、ジンジャービアで満たす。ライムウェッジを添える。",
   note:"1941年ハリウッド。ウォッカの普及とジンジャービアの在庫消化のため誕生した。"},
  {id:4, name:"Bloody Mary", nameJa:"ブラッディ・メアリー", base:"ウォッカ", taste:"辛口", glass:"ハイボールグラス",
   color1:"#c0392b", color2:"#922b21", abv:12, iba:true, era:"クラシック",
   photo:"bloody mary tomato cocktail spicy",
   flavor:{sweet:0,sour:2,bitter:1,strong:2,fresh:2,complex:4},
   ingredients:[["ウォッカ","45ml"],["トマトジュース","90ml"],["フレッシュレモンジュース","15ml"],["ウスターソース","2dash"],["タバスコ","2dash"],["セロリソルト","1pinch"],["黒胡椒","1pinch"]],
   method:"材料をステアし、氷の入ったグラスに注ぐ。セロリ、レモンウェッジを添える。",
   note:"1920年代パリのヘリーズ・ニューヨーク・バーで誕生。「二日酔いの特効薬」として知られる。"},
  {id:5, name:"Black Russian", nameJa:"ブラック・ルシアン", base:"ウォッカ", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#1c0f08", color2:"#3d1f0e", abv:28, iba:true, era:"クラシック",
   photo:"black russian coffee vodka cocktail",
   flavor:{sweet:3,sour:0,bitter:3,strong:4,fresh:0,complex:2},
   ingredients:[["ウォッカ","50ml"],["コーヒーリキュール（カルーア）","20ml"]],
   method:"氷の入ったオールドファッションドグラスに両材料を注ぎ、軽くステアする。",
   note:"1949年ブリュッセルのメトロポールホテル。バーテンダーのグスタフ・トップスが米国大使のために考案。"},
  {id:6, name:"White Russian", nameJa:"ホワイト・ルシアン", base:"ウォッカ", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#e8d5a3", color2:"#c4a96d", abv:18, iba:true, era:"クラシック",
   photo:"white russian cream cocktail",
   flavor:{sweet:4,sour:0,bitter:2,strong:3,fresh:0,complex:2},
   ingredients:[["ウォッカ","50ml"],["コーヒーリキュール","20ml"],["生クリーム","30ml"]],
   method:"氷の入ったグラスにウォッカとリキュールを注ぎ、生クリームをゆっくりフロートさせる。",
   note:"映画「ビッグ・リボウスキ」（1998）で一躍有名に。ブラック・ルシアンの派生形。"},
  {id:7, name:"Sex on the Beach", nameJa:"セックス・オン・ザ・ビーチ", base:"ウォッカ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ff9500", color2:"#e8547a", abv:11, iba:true, era:"モダン",
   photo:"tropical cocktail orange peach beach",
   flavor:{sweet:4,sour:1,bitter:0,strong:1,fresh:3,complex:1},
   ingredients:[["ウォッカ","40ml"],["ピーチシュナップス","20ml"],["オレンジジュース","40ml"],["クランベリージュース","40ml"]],
   method:"氷の入ったハイボールグラスにすべての材料を注ぎ、軽くステアする。オレンジスライスを添える。",
   note:"1987年フロリダ生まれ。ビーチカルチャーを体現したトロピカルなロングドリンク。"},
  {id:8, name:"Harvey Wallbanger", nameJa:"ハーヴェイ・ウォールバンガー", base:"ウォッカ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ff9500", color2:"#f57c00", abv:12, iba:true, era:"クラシック",
   photo:"harvey wallbanger orange cocktail",
   flavor:{sweet:3,sour:1,bitter:1,strong:2,fresh:3,complex:2},
   ingredients:[["ウォッカ","35ml"],["フレッシュオレンジジュース","100ml"],["ガリアーノ（フロート）","15ml"]],
   method:"氷の入ったグラスにウォッカとOJを注ぎ、ガリアーノをゆっくりフロートさせる。",
   note:"1970年代に米国で爆発的人気。サーファーのハーヴェイが壁に頭をぶつけるほど飲んだことが名前の由来。"},

  // ===== ジン =====
  {id:9, name:"Dry Martini", nameJa:"ドライ・マティーニ", base:"ジン", taste:"辛口", glass:"カクテルグラス",
   color1:"#d4e8f0", color2:"#90caf9", abv:38, iba:true, era:"クラシック",
   photo:"dry martini gin olive cocktail",
   flavor:{sweet:0,sour:0,bitter:1,strong:5,fresh:1,complex:3},
   ingredients:[["ドライジン","60ml"],["ドライベルモット","10ml"]],
   method:"氷を入れたミキシンググラスでステアし、冷やしたカクテルグラスに注ぐ。グリーンオリーブを添える。",
   note:"「カクテルの王様」。ウィンストン・チャーチルは「ベルモットのビンを眺めながらジンを飲む」と言ったとされる。"},
  {id:10, name:"Gin & Tonic", nameJa:"ジン・トニック", base:"ジン", taste:"辛口", glass:"ハイボールグラス",
   color1:"#e8f8e8", color2:"#a8d8a8", abv:11, iba:false, era:"クラシック",
   photo:"gin tonic lime bubbles cocktail",
   flavor:{sweet:1,sour:1,bitter:2,strong:2,fresh:5,complex:1},
   ingredients:[["ドライジン","45ml"],["トニックウォーター","150ml"]],
   method:"氷の入ったグラスにジンを注ぎ、冷えたトニックウォーターで静かに満たす。ライムウェッジを添える。",
   note:"19世紀英国植民地時代にマラリア予防薬のキニーネ（トニック）をジンで飲みやすくしたのが起源。"},
  {id:11, name:"Negroni", nameJa:"ネグローニ", base:"ジン", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#c0392b", color2:"#7b241c", abv:24, iba:true, era:"クラシック",
   photo:"negroni campari vermouth cocktail",
   flavor:{sweet:2,sour:0,bitter:5,strong:3,fresh:1,complex:4},
   ingredients:[["ドライジン","30ml"],["カンパリ","30ml"],["スイートベルモット","30ml"]],
   method:"氷の入ったオールドファッションドグラスで全材料をステアする。オレンジスライスを添える。",
   note:"1919年フィレンツェ。カミロ・ネグローニ伯爵が「アメリカーノをもっと強く」とリクエストしたのが起源。"},
  {id:12, name:"Tom Collins", nameJa:"トム・コリンズ", base:"ジン", taste:"酸味", glass:"コリンズグラス",
   color1:"#e8f8e8", color2:"#c8e6c9", abv:9, iba:true, era:"クラシック",
   photo:"tom collins gin lemon soda cocktail",
   flavor:{sweet:2,sour:3,bitter:0,strong:1,fresh:5,complex:1},
   ingredients:[["ロンドン・ドライジン","45ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["ソーダ水","60ml"]],
   method:"ジン、レモン、シロップをシェイクし、氷の入ったコリンズグラスに注ぎ、ソーダを加える。",
   note:"1876年の「バーテンダーズ・ガイド」に初登場。ロングドリンクの基本形の一つ。"},
  {id:13, name:"Singapore Sling", nameJa:"シンガポール・スリング", base:"ジン", taste:"甘口", glass:"コリンズグラス",
   color1:"#e8547a", color2:"#ad1457", abv:15, iba:true, era:"クラシック",
   photo:"singapore sling pink cocktail tropical",
   flavor:{sweet:4,sour:2,bitter:1,strong:2,fresh:3,complex:4},
   ingredients:[["ジン","30ml"],["チェリーブランデー","15ml"],["コアントロー","7.5ml"],["ベネディクティン","7.5ml"],["パイナップルジュース","120ml"],["ライムジュース","15ml"],["グレナデン","10ml"],["アンゴスチュラビターズ","1dash"]],
   method:"全材料をシェイクし、氷の入ったコリンズグラスに注ぐ。パイナップルスライスとチェリーを飾る。",
   note:"1915年頃シンガポールのラッフルズホテルでNgiam Tong Boonが考案。現在も同ホテルの名物。"},
  {id:14, name:"Last Word", nameJa:"ラスト・ワード", base:"ジン", taste:"酸味", glass:"カクテルグラス",
   color1:"#b8e986", color2:"#7cb342", abv:28, iba:false, era:"クラシック",
   photo:"last word green chartreuse cocktail",
   flavor:{sweet:2,sour:3,bitter:1,strong:4,fresh:3,complex:5},
   ingredients:[["ジン","22.5ml"],["グリーン・シャルトリューズ","22.5ml"],["マラスキーノ","22.5ml"],["フレッシュライムジュース","22.5ml"]],
   method:"全材料を等量シェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"1920年代デトロイト・アスレチック・クラブで誕生。禁酒法時代に忘れられ、2000年代にシアトルで再発見された。"},
  {id:15, name:"Aviation", nameJa:"アビエーション", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#9b59b6", color2:"#6c3483", abv:24, iba:true, era:"クラシック",
   photo:"aviation cocktail purple violet",
   flavor:{sweet:3,sour:2,bitter:0,strong:3,fresh:2,complex:4},
   ingredients:[["ジン","45ml"],["マラスキーノ","15ml"],["クレーム・ド・ヴィオレット","7.5ml"],["フレッシュレモンジュース","15ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"1916年初登場。バイオレットリキュールが幻となり長く廃れたが、2000年代の復刻で復活。"},
  {id:16, name:"Clover Club", nameJa:"クローバー・クラブ", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#e8547a", color2:"#ad1457", abv:20, iba:true, era:"クラシック",
   photo:"clover club raspberry cocktail pink",
   flavor:{sweet:3,sour:2,bitter:0,strong:2,fresh:2,complex:3},
   ingredients:[["ロンドン・ドライジン","45ml"],["フレッシュレモンジュース","15ml"],["ラズベリーシロップ","15ml"],["卵白","1個分"]],
   method:"ドライシェイク（氷なし）後、氷を加えて再度シェイク。冷やしたカクテルグラスに注ぐ。",
   note:"20世紀初頭フィラデルフィアの名士クラブが発祥。卵白が生み出すシルキーな泡が特徴。"},
  {id:17, name:"Bramble", nameJa:"ブランブル", base:"ジン", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#7b1fa2", color2:"#4a148c", abv:18, iba:true, era:"モダン",
   photo:"bramble blackberry gin cocktail",
   flavor:{sweet:3,sour:2,bitter:0,strong:2,fresh:3,complex:3},
   ingredients:[["ロンドン・ドライジン","50ml"],["フレッシュレモンジュース","25ml"],["砂糖シロップ","12.5ml"],["クレーム・ド・ミュール（フロート）","15ml"]],
   method:"ジン、レモン、シロップをシェイクし、砕いた氷の入ったグラスに注ぐ。クレーム・ド・ミュールをゆっくりフロート。ブラックベリーとレモンスライスを飾る。",
   note:"1984年ロンドンのファウンダーズ・バーでディック・ブラッドセルが考案。英国ジンカクテルの傑作。"},
  {id:18, name:"Martinez", nameJa:"マルティネス", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:30, iba:true, era:"クラシック",
   photo:"martinez cocktail cherry vintage",
   flavor:{sweet:3,sour:0,bitter:1,strong:4,fresh:0,complex:4},
   ingredients:[["オールドトムジン","45ml"],["スイートベルモット","45ml"],["マラスキーノ","7.5ml"],["オレンジビターズ","2dash"]],
   method:"ミキシンググラスに全材料と氷を入れてステアし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"1884年初出。マティーニの直接の祖先とされる19世紀最重要カクテルの一つ。"},
  {id:19, name:"Hanky Panky", nameJa:"ハンキー・パンキー", base:"ジン", taste:"苦味", glass:"カクテルグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:28, iba:true, era:"クラシック",
   photo:"hanky panky cocktail vermouth",
   flavor:{sweet:2,sour:0,bitter:4,strong:4,fresh:0,complex:5},
   ingredients:[["ロンドン・ドライジン","45ml"],["スイートベルモット","45ml"],["フェルネット・ブランカ","7.5ml"]],
   method:"ミキシンググラスでステアし、冷やしたカクテルグラスに注ぐ。オレンジツイストを添える。",
   note:"1925年ロンドン・サボイホテルのアダ・コールマンが俳優チャールズ・ハーリーのためにに考案。"},
  {id:20, name:"Ramos Gin Fizz", nameJa:"ラモス・ジン・フィズ", base:"ジン", taste:"甘口", glass:"コリンズグラス",
   color1:"#f5f5f5", color2:"#e0e0e0", abv:12, iba:false, era:"クラシック",
   photo:"gin fizz cream frothy cocktail",
   flavor:{sweet:3,sour:2,bitter:0,strong:1,fresh:4,complex:4},
   ingredients:[["ジン","45ml"],["フレッシュレモンジュース","15ml"],["フレッシュライムジュース","15ml"],["砂糖シロップ","30ml"],["卵白","1個分"],["生クリーム","45ml"],["オレンジフラワーウォーター","3dash"],["ソーダ水","45ml"]],
   method:"ソーダ以外を最低12分間シェイク。コリンズグラスに注ぎ、ソーダをゆっくり加える。",
   note:"1888年ニューオーリンズのヘンリー・ラモスが考案。長時間シェイクを要する究極の手間ヒマカクテル。"},

  // ===== ラム =====
  {id:21, name:"Mojito", nameJa:"モヒート", base:"ラム", taste:"甘口", glass:"ハイボールグラス",
   color1:"#a8d8a8", color2:"#4caf50", abv:10, iba:true, era:"クラシック",
   photo:"mojito mint lime rum cocktail",
   flavor:{sweet:2,sour:2,bitter:0,strong:1,fresh:5,complex:2},
   ingredients:[["ホワイトラム","45ml"],["フレッシュライムジュース","20ml"],["砂糖（白）","2tsp"],["フレッシュミント","10枚"],["ソーダ水","適量"]],
   method:"ミントと砂糖をグラスでムドル（押しつぶす）。ライムジュースとラムを加え、氷を入れ、ソーダで満たす。ミントを飾る。",
   note:"キューバ・ハバナ生まれ。ヘミングウェイも愛したカクテル。名前はスペイン語の「mojo」（魔法）に由来とも。"},
  {id:22, name:"Daiquiri", nameJa:"ダイキリ", base:"ラム", taste:"酸味", glass:"カクテルグラス",
   color1:"#d4e8f0", color2:"#81d4fa", abv:26, iba:true, era:"クラシック",
   photo:"daiquiri rum lime cocktail classic",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:4,complex:2},
   ingredients:[["ホワイトラム","60ml"],["フレッシュライムジュース","20ml"],["砂糖シロップ","10ml"]],
   method:"全材料を強くシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"キューバの鉱山町ダイキリが発祥。JFKとヘミングウェイが愛したシンプルさゆえに技術が問われる名作。"},
  {id:23, name:"Piña Colada", nameJa:"ピニャ・コラーダ", base:"ラム", taste:"甘口", glass:"ゴブレット",
   color1:"#fff9e6", color2:"#ffe082", abv:13, iba:true, era:"クラシック",
   photo:"pina colada pineapple coconut tropical",
   flavor:{sweet:5,sour:1,bitter:0,strong:2,fresh:3,complex:2},
   ingredients:[["ホワイトラム","30ml"],["ゴールドラム","30ml"],["フレッシュパイナップルジュース","90ml"],["ココナッツクリーム","30ml"]],
   method:"全材料をブレンダーで砕いた氷と共にブレンドし、グラスに注ぐ。パイナップルとチェリーを飾る。",
   note:"プエルトリコの国民的カクテル。1954年ラモン・マレロが考案とされる。「パイナップルの絞り汁」の意。"},
  {id:24, name:"Cuba Libre", nameJa:"キューバ・リブレ", base:"ラム", taste:"甘口", glass:"ハイボールグラス",
   color1:"#3d1f0e", color2:"#1c0f08", abv:12, iba:true, era:"クラシック",
   photo:"cuba libre rum cola lime cocktail",
   flavor:{sweet:3,sour:1,bitter:0,strong:2,fresh:2,complex:1},
   ingredients:[["ゴールドラム","50ml"],["コーラ","120ml"],["フレッシュライムジュース","10ml"]],
   method:"ライムをグラスに搾り、氷を入れ、ラムを注ぎ、コーラで満たす。ライムウェッジを添える。",
   note:"1900年頃キューバ独立戦争後に誕生。スペインからの独立「自由なキューバ」を祝って乾杯されたのが起源。"},
  {id:25, name:"Mai Tai", nameJa:"マイ・タイ", base:"ラム", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#ff9500", color2:"#f57c00", abv:18, iba:true, era:"クラシック",
   photo:"mai tai tiki rum tropical cocktail",
   flavor:{sweet:3,sour:2,bitter:0,strong:3,fresh:3,complex:4},
   ingredients:[["ホワイトラム","30ml"],["ダークラム（フロート）","30ml"],["オレンジキュラソー","15ml"],["オルジャータ（アーモンドシロップ）","15ml"],["フレッシュライムジュース","30ml"]],
   method:"ダーク以外をシェイクし、砕いた氷の入ったグラスに注ぐ。ダークラムをフロート。ミントとライムを飾る。",
   note:"1944年トレーダー・ヴィックが考案。タヒチ語で「この世のものではない、素晴らしい」の意。"},
  {id:26, name:"Hemingway Daiquiri", nameJa:"ヘミングウェイ・ダイキリ", base:"ラム", taste:"酸味", glass:"カクテルグラス",
   color1:"#e8f4c8", color2:"#aed581", abv:24, iba:true, era:"クラシック",
   photo:"hemingway daiquiri grapefruit rum",
   flavor:{sweet:0,sour:4,bitter:1,strong:3,fresh:4,complex:3},
   ingredients:[["ホワイトラム","60ml"],["フレッシュグレープフルーツジュース","40ml"],["マラスキーノ","15ml"],["フレッシュライムジュース","15ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"ヘミングウェイが糖尿病のため砂糖なしでダイキリを注文したのがルーツ。ハバナのラ・フロリディータで生まれた。"},
  {id:27, name:"Zombie", nameJa:"ゾンビ", base:"ラム", taste:"甘口", glass:"コリンズグラス",
   color1:"#ff9500", color2:"#e65100", abv:22, iba:true, era:"クラシック",
   photo:"zombie rum tropical tiki cocktail",
   flavor:{sweet:3,sour:2,bitter:1,strong:5,fresh:2,complex:4},
   ingredients:[["ゴールドラム","45ml"],["ダークラム","30ml"],["151プルーフラム","15ml"],["フレッシュライムジュース","20ml"],["グレナデン","10ml"],["アプリコットブランデー","15ml"]],
   method:"全材料をシェイクし、砕いた氷の入ったコリンズグラスに注ぐ。ミントとパイナップルを飾る。",
   note:"1930年代ドン・ザ・ビーチコマーが考案。強烈なアルコール度数から「1杯まで」が同店のルールだった。"},
  {id:28, name:"Dark & Stormy", nameJa:"ダーク・アンド・ストーミー", base:"ラム", taste:"辛口", glass:"ハイボールグラス",
   color1:"#3e2723", color2:"#1a0f0a", abv:12, iba:false, era:"モダン",
   photo:"dark stormy rum ginger beer",
   flavor:{sweet:1,sour:1,bitter:0,strong:2,fresh:4,complex:2},
   ingredients:[["ゴスリングス・ブラックシール・ラム（フロート）","60ml"],["ジンジャービア","100ml"],["フレッシュライムジュース","15ml"]],
   method:"氷の入ったハイボールグラスにライムとジンジャービアを注ぎ、ラムをフロートさせる。",
   note:"バミューダ発祥。ゴスリングスラムが商標登録しており、公式にはゴスリングス使用が定義。"},

  // ===== テキーラ =====
  {id:29, name:"Margarita", nameJa:"マルガリータ", base:"テキーラ", taste:"酸味", glass:"カクテルグラス",
   color1:"#e8f8e8", color2:"#a8d8a8", abv:24, iba:true, era:"クラシック",
   photo:"margarita tequila lime salt cocktail",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:4,complex:2},
   ingredients:[["テキーラ（ブランコ）","50ml"],["コアントロー","20ml"],["フレッシュライムジュース","15ml"]],
   method:"グラスのリムを塩でスノースタイルに。全材料をシェイクし、カクテルグラスに注ぐ。",
   note:"世界で最も多く注文されるカクテルの一つ。1930〜40年代メキシコで誕生、複数の「考案者」が存在する。"},
  {id:30, name:"Paloma", nameJa:"パロマ", base:"テキーラ", taste:"酸味", glass:"ハイボールグラス",
   color1:"#ffb3ba", color2:"#ff6b6b", abv:11, iba:false, era:"クラシック",
   photo:"paloma tequila grapefruit cocktail",
   flavor:{sweet:1,sour:3,bitter:1,strong:2,fresh:5,complex:1},
   ingredients:[["テキーラ（ブランコ）","50ml"],["グレープフルーツソーダ","150ml"],["フレッシュライムジュース","15ml"],["塩","適量"]],
   method:"塩でリムを作り、氷の入ったグラスにテキーラとライムを注ぎ、グレープフルーツソーダで満たす。",
   note:"メキシコで最も愛されるテキーラカクテル。「ハト」を意味するスペイン語。マルガリータより親しまれている。"},
  {id:31, name:"Tequila Sunrise", nameJa:"テキーラ・サンライズ", base:"テキーラ", taste:"甘口", glass:"コリンズグラス",
   color1:"#ff9500", color2:"#c0392b", abv:12, iba:true, era:"クラシック",
   photo:"tequila sunrise orange gradient cocktail",
   flavor:{sweet:3,sour:1,bitter:0,strong:2,fresh:3,complex:1},
   ingredients:[["テキーラ（ブランコ）","45ml"],["フレッシュオレンジジュース","90ml"],["グレナデン","15ml"]],
   method:"氷の入ったグラスにテキーラとOJを注ぎ、グレナデンをゆっくりと底に沈める。かき混ぜずに提供。",
   note:"日の出のグラデーションが美しいビジュアルカクテル。1970年代ローリング・ストーンズも愛飲した。"},
  {id:32, name:"Tommy's Margarita", nameJa:"トミーズ・マルガリータ", base:"テキーラ", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#e8f8e8", color2:"#66bb6a", abv:22, iba:true, era:"モダン",
   photo:"margarita tequila agave cocktail",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:4,complex:3},
   ingredients:[["100%アガベテキーラ（ブランコ）","60ml"],["フレッシュライムジュース","30ml"],["アガベシロップ","15ml"]],
   method:"全材料をシェイクし、岩塩リムの砕いた氷入りグラスに注ぐ。",
   note:"1990年代サンフランシスコのトミーズ・メキシカンで誕生。テキーラの本質を引き出すモダン・クラシック。"},
  {id:33, name:"Mezcal Negroni", nameJa:"メスカル・ネグローニ", base:"テキーラ", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:25, iba:false, era:"モダン",
   photo:"mezcal negroni smoky cocktail",
   flavor:{sweet:2,sour:0,bitter:5,strong:3,fresh:0,complex:5},
   ingredients:[["メスカル","30ml"],["カンパリ","30ml"],["スイートベルモット","30ml"]],
   method:"全材料を氷と共にミキシンググラスでステアし、オールドファッションドグラスに注ぐ。オレンジピールを添える。",
   note:"ネグローニのメスカルバージョン。スモーキーで複雑な深みが増す、近年人気急上昇の一杯。"},

  // ===== ウイスキー =====
  {id:34, name:"Old Fashioned", nameJa:"オールド・ファッションド", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#c97b3c", color2:"#8d4e14", abv:35, iba:true, era:"クラシック",
   photo:"old fashioned bourbon whiskey cocktail",
   flavor:{sweet:2,sour:0,bitter:2,strong:5,fresh:0,complex:3},
   ingredients:[["バーボンまたはライウイスキー","60ml"],["砂糖（白）","1tsp"],["アンゴスチュラビターズ","2dash"],["ウォーター","少量"]],
   method:"グラスに砂糖とビターズを入れ少量の水で溶かす。大きな氷を1個入れ、ウイスキーを注いでゆっくりステア。オレンジピールを添える。",
   note:"カクテルの原点。1806年の「カクテル」の定義（スピリッツ+砂糖+ビターズ+水）をそのまま体現する不朽の名作。"},
  {id:35, name:"Manhattan", nameJa:"マンハッタン", base:"ウイスキー", taste:"甘口", glass:"カクテルグラス",
   color1:"#c97b3c", color2:"#6d2f0e", abv:30, iba:true, era:"クラシック",
   photo:"manhattan whiskey vermouth cocktail cherry",
   flavor:{sweet:3,sour:0,bitter:2,strong:4,fresh:0,complex:4},
   ingredients:[["ライウイスキー","50ml"],["スイートベルモット","20ml"],["アンゴスチュラビターズ","2dash"]],
   method:"ミキシンググラスに全材料と氷を入れてステアし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"1880年代ニューヨーク・マンハッタン島が発祥。「チャーチルの母が考案」説は誤りとされている。"},
  {id:36, name:"Whiskey Sour", nameJa:"ウイスキー・サワー", base:"ウイスキー", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#f5c842", color2:"#f39c12", abv:20, iba:true, era:"クラシック",
   photo:"whiskey sour lemon bourbon cocktail",
   flavor:{sweet:2,sour:4,bitter:0,strong:3,fresh:3,complex:2},
   ingredients:[["バーボン","45ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["卵白","1個分（任意）"]],
   method:"全材料をシェイクし、氷の入ったグラスに注ぐ。オレンジスライスとチェリーを飾る。",
   note:"サワー系カクテルの基本形。卵白を入れた場合は「ボストン・サワー」とも呼ばれる。"},
  {id:37, name:"Penicillin", nameJa:"ペニシリン", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#f5c842", color2:"#d4a017", abv:20, iba:false, era:"モダン",
   photo:"penicillin scotch whisky cocktail",
   flavor:{sweet:2,sour:3,bitter:1,strong:3,fresh:3,complex:5},
   ingredients:[["スコッチ（ブレンデッド）","45ml"],["アイラシングルモルト（フロート）","7.5ml"],["フレッシュレモンジュース","22.5ml"],["生姜シロップ","22.5ml"],["蜂蜜シロップ","22.5ml"]],
   method:"アイラ以外をシェイクし、砕いた氷の入ったグラスに注ぐ。アイラをフロート。生姜を飾る。",
   note:"2005年ニューヨーク「PDT」でサム・ロスが考案。スコッチの風味を最大限に引き出すモダン・クラシックの傑作。"},
  {id:38, name:"Boulevardier", nameJa:"ブールヴァルディエ", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:28, iba:false, era:"クラシック",
   photo:"boulevardier bourbon campari cocktail",
   flavor:{sweet:2,sour:0,bitter:4,strong:4,fresh:0,complex:4},
   ingredients:[["バーボン","45ml"],["カンパリ","30ml"],["スイートベルモット","30ml"]],
   method:"全材料を氷と共にミキシンググラスでステアし、グラスに注ぐ。オレンジピールを添える。",
   note:"1920年代パリ生まれ。ネグローニのバーボンバージョン。「都会人」を意味するフランス語が名前の由来。"},
  {id:39, name:"Sazerac", nameJa:"サゼラック", base:"ウイスキー", taste:"辛口", glass:"オールドファッションドグラス",
   color1:"#c97b3c", color2:"#8d4e14", abv:35, iba:true, era:"クラシック",
   photo:"sazerac rye whiskey new orleans cocktail",
   flavor:{sweet:1,sour:0,bitter:3,strong:5,fresh:1,complex:4},
   ingredients:[["ライウイスキー（またはコニャック）","60ml"],["砂糖","1tsp"],["ペイショーズビターズ","3dash"],["アブサン","rinse用"]],
   method:"アブサンでグラスをリンスし余分を捨てる。砂糖とビターズを溶かし、ウイスキーと氷でステアしグラスに注ぐ。レモンピール。",
   note:"1850年代ニューオーリンズ生まれ。アメリカ最古のカクテルの一つ。ニューオーリンズ市の公式カクテル。"},
  {id:40, name:"Mint Julep", nameJa:"ミント・ジュレップ", base:"ウイスキー", taste:"甘口", glass:"ハイボールグラス",
   color1:"#a8d8a8", color2:"#66bb6a", abv:20, iba:true, era:"クラシック",
   photo:"mint julep bourbon mint cup cocktail",
   flavor:{sweet:2,sour:0,bitter:0,strong:3,fresh:5,complex:2},
   ingredients:[["バーボン","60ml"],["砂糖シロップ","10ml"],["フレッシュミント","10枚以上"],["パウダーシュガー","適量"]],
   method:"ミントと砂糖シロップをグラスで軽くムドル。バーボンを注ぎ、砕いた氷で満たす。ミントを束ねて飾りパウダーシュガーを振る。",
   note:"ケンタッキーダービーの公式カクテル。毎年約12万杯が消費される。南部の「おもてなし」の象徴。"},
  {id:41, name:"Paper Plane", nameJa:"ペーパー・プレーン", base:"ウイスキー", taste:"苦味", glass:"カクテルグラス",
   color1:"#f0a800", color2:"#e65100", abv:26, iba:false, era:"モダン",
   photo:"paper plane bourbon cocktail equal parts",
   flavor:{sweet:2,sour:3,bitter:3,strong:3,fresh:2,complex:4},
   ingredients:[["バーボン","22.5ml"],["アペロール","22.5ml"],["アメール・ピコン","22.5ml"],["フレッシュレモンジュース","22.5ml"]],
   method:"全材料を等量シェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"2008年NYのサム・ロスが考案。M.I.Aの楽曲からネーミング。4素材等量の均衡が美しい現代の傑作。"},
  {id:42, name:"New York Sour", nameJa:"ニューヨーク・サワー", base:"ウイスキー", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#8b1a1a", color2:"#6d1414", abv:20, iba:false, era:"クラシック",
   photo:"new york sour red wine bourbon cocktail",
   flavor:{sweet:2,sour:4,bitter:1,strong:3,fresh:3,complex:3},
   ingredients:[["バーボン","60ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["赤ワイン（フロート）","15ml"]],
   method:"バーボン、レモン、シロップをシェイクし、グラスに注ぐ。ワインをゆっくりフロート。",
   note:"1880年代シカゴで誕生。ウイスキー・サワーに赤ワインフロートを加えた視覚的にも美しい傑作。"},

  // ===== ブランデー =====
  {id:43, name:"Sidecar", nameJa:"サイドカー", base:"ブランデー", taste:"酸味", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:28, iba:true, era:"クラシック",
   photo:"sidecar cognac lemon cocktail",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:3,complex:3},
   ingredients:[["コニャック","50ml"],["コアントロー","20ml"],["フレッシュレモンジュース","20ml"]],
   method:"砂糖でスノースタイル（任意）。全材料をシェイクし、冷やしたカクテルグラスに注ぐ。レモンピール。",
   note:"第一次大戦後パリのリッツホテルで誕生とされる。コニャック系カクテルの最高峰。バランスが難しい名作。"},
  {id:44, name:"French 75", nameJa:"フレンチ75", base:"ジン", taste:"酸味", glass:"シャンパングラス",
   color1:"#fff9e6", color2:"#ffe082", abv:14, iba:true, era:"クラシック",
   photo:"french 75 champagne gin lemon cocktail",
   flavor:{sweet:1,sour:3,bitter:0,strong:2,fresh:5,complex:3},
   ingredients:[["ジン（またはコニャック）","30ml"],["フレッシュレモンジュース","15ml"],["砂糖シロップ","10ml"],["シャンパン","60ml"]],
   method:"ジン、レモン、シロップをシェイクしシャンパングラスに注ぎ、シャンパンで満たす。レモンツイスト。",
   note:"WWI時代にフランス軍の75mm野砲にちなんで命名。打ち出すような強烈なパンチが名前の由来。"},
  {id:45, name:"Brandy Alexander", nameJa:"ブランデー・アレキサンダー", base:"ブランデー", taste:"甘口", glass:"カクテルグラス",
   color1:"#e8d5a3", color2:"#c4a96d", abv:22, iba:true, era:"クラシック",
   photo:"brandy alexander cream cognac cocktail",
   flavor:{sweet:4,sour:0,bitter:1,strong:3,fresh:0,complex:3},
   ingredients:[["コニャック","30ml"],["クレーム・ド・カカオ（ダーク）","30ml"],["生クリーム","30ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。ナツメグを振る。",
   note:"1970年代のジョン・レノンのお気に入り。デザートカクテルの最高峰として今なお親しまれる。"},
  {id:46, name:"Pisco Sour", nameJa:"ピスコ・サワー", base:"ブランデー", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#e8d5a3", color2:"#c4a96d", abv:22, iba:true, era:"クラシック",
   photo:"pisco sour peru cocktail frothy",
   flavor:{sweet:2,sour:4,bitter:2,strong:3,fresh:3,complex:3},
   ingredients:[["ピスコ","60ml"],["フレッシュライムジュース","30ml"],["砂糖シロップ","20ml"],["卵白","1個分"],["アンゴスチュラビターズ","3dash"]],
   method:"全材料をドライシェイク後、氷を加えて再シェイク。グラスに注ぎビターズを3滴垂らす。",
   note:"ペルーとチリ両国が「国民的カクテル」として主張する南米を代表する一杯。"},

  // ===== リキュール/ワインベース =====
  {id:47, name:"Aperol Spritz", nameJa:"アペロール・スプリッツ", base:"リキュール", taste:"苦味", glass:"ゴブレット",
   color1:"#ff9500", color2:"#e65100", abv:8, iba:false, era:"モダン",
   photo:"aperol spritz orange wine cocktail",
   flavor:{sweet:2,sour:1,bitter:3,strong:1,fresh:4,complex:2},
   ingredients:[["プロセッコ","90ml"],["アペロール","60ml"],["ソーダ水","30ml"]],
   method:"氷の入ったワイングラスにプロセッコ、アペロール、ソーダを3:2:1で注ぐ。オレンジスライスを添える。",
   note:"イタリア・ヴェネト州発祥。「スプリッツ」とは地元の「ひと吹き（スプラッシュ）」の意。アペリティーヴォの定番。"},
  {id:48, name:"Americano", nameJa:"アメリカーノ", base:"リキュール", taste:"苦味", glass:"ハイボールグラス",
   color1:"#c0392b", color2:"#7b241c", abv:10, iba:true, era:"クラシック",
   photo:"americano campari vermouth soda cocktail",
   flavor:{sweet:1,sour:0,bitter:4,strong:1,fresh:3,complex:3},
   ingredients:[["カンパリ","30ml"],["スイートベルモット","30ml"],["ソーダ水","適量"]],
   method:"氷の入ったグラスにカンパリとベルモットを注ぎ、ソーダで満たす。オレンジスライスを添える。",
   note:"1860年代ミラノのカフェ・カンパリで誕生。ネグローニの前身。アメリカ人の好みに合わせソーダを足した説あり。"},
  {id:49, name:"Bellini", nameJa:"ベリーニ", base:"ワイン", taste:"甘口", glass:"シャンパングラス",
   color1:"#ffb3ba", color2:"#ff6b6b", abv:7, iba:true, era:"クラシック",
   photo:"bellini prosecco peach cocktail",
   flavor:{sweet:4,sour:1,bitter:0,strong:1,fresh:4,complex:2},
   ingredients:[["プロセッコ","100ml"],["白桃ピューレ（生）","50ml"]],
   method:"冷やしたシャンパングラスに白桃ピューレを入れ、プロセッコをゆっくり注ぐ。",
   note:"1948年ヴェネツィアのハリーズ・バーでジュゼッペ・チプリアーニが考案。画家ジョヴァンニ・ベリーニに捧げた。"},
  {id:50, name:"Kir Royale", nameJa:"キール・ロワイヤル", base:"ワイン", taste:"甘口", glass:"シャンパングラス",
   color1:"#e8547a", color2:"#ad1457", abv:10, iba:false, era:"クラシック",
   photo:"kir royale champagne cassis cocktail",
   flavor:{sweet:3,sour:1,bitter:0,strong:1,fresh:3,complex:2},
   ingredients:[["シャンパン","150ml"],["クレーム・ド・カシス","15ml"]],
   method:"冷やしたシャンパングラスにカシスを入れ、シャンパンをゆっくり注ぐ。",
   note:"ブルゴーニュのキール市長（フェリックス・キール）が愛した「キール」のシャンパン版。"},
  {id:51, name:"Negroni Sbagliato", nameJa:"ネグローニ・ズバリャート", base:"ワイン", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#c0392b", color2:"#7b241c", abv:13, iba:false, era:"モダン",
   photo:"negroni sbagliato prosecco campari",
   flavor:{sweet:2,sour:1,bitter:4,strong:2,fresh:3,complex:3},
   ingredients:[["カンパリ","30ml"],["スイートベルモット","30ml"],["プロセッコ","30ml"]],
   method:"氷の入ったグラスにカンパリとベルモットを注ぎ、プロセッコで満たす。オレンジスライスを添える。",
   note:"「失敗したネグローニ」の意。バーテンダーが誤ってジンのかわりにプロセッコを入れて誕生したとされる。"},

  // ===== 追加クラシック/モダン =====
  {id:52, name:"Gimlet", nameJa:"ギムレット", base:"ジン", taste:"酸味", glass:"カクテルグラス",
   color1:"#b8e986", color2:"#7cb342", abv:28, iba:true, era:"クラシック",
   photo:"gimlet gin lime cocktail",
   flavor:{sweet:2,sour:3,bitter:0,strong:4,fresh:3,complex:2},
   ingredients:[["ロンドン・ドライジン","60ml"],["フレッシュライムジュース","20ml"],["砂糖シロップ","10ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。ライムスライスを添える。",
   note:"「ギムレットには早すぎた」— チャンドラー「長いお別れ」。英国海軍の壊血病予防飲料が起源。"},
  {id:53, name:"Bee's Knees", nameJa:"ビーズ・ニーズ", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:26, iba:false, era:"クラシック",
   photo:"bees knees gin honey lemon cocktail",
   flavor:{sweet:3,sour:3,bitter:0,strong:3,fresh:3,complex:2},
   ingredients:[["ジン","60ml"],["蜂蜜シロップ","22.5ml"],["フレッシュレモンジュース","22.5ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。レモンツイストを添える。",
   note:"禁酒法時代に粗悪なジンの臭いをマスクするために生まれた。「最高のもの」を意味する俗語が名前の由来。"},
  {id:54, name:"Gold Rush", nameJa:"ゴールド・ラッシュ", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#f5c842", color2:"#d4a017", abv:22, iba:false, era:"モダン",
   photo:"gold rush bourbon honey lemon cocktail",
   flavor:{sweet:3,sour:3,bitter:0,strong:3,fresh:3,complex:2},
   ingredients:[["バーボン","60ml"],["蜂蜜シロップ","22.5ml"],["フレッシュレモンジュース","22.5ml"]],
   method:"全材料をシェイクし、砕いた氷の入ったグラスに注ぐ。",
   note:"2000年代初頭NYの「Milk & Honey」で誕生。ビーズ・ニーズのバーボン版。"},
  {id:55, name:"Trinidad Sour", nameJa:"トリニダード・サワー", base:"リキュール", taste:"苦味", glass:"カクテルグラス",
   color1:"#c0392b", color2:"#7b241c", abv:20, iba:false, era:"モダン",
   photo:"trinidad sour bitters cocktail",
   flavor:{sweet:2,sour:3,bitter:5,strong:2,fresh:2,complex:5},
   ingredients:[["アンゴスチュラビターズ","30ml"],["オルジャータ","30ml"],["フレッシュレモンジュース","22.5ml"],["ライウイスキー","7.5ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"「ビターズが主役」という革命的構造。2009年NYのジュゼッペ・ゴンザレスが考案した衝撃作。"},
  {id:56, name:"Irish Coffee", nameJa:"アイリッシュ・コーヒー", base:"ウイスキー", taste:"甘口", glass:"マグカップ",
   color1:"#2c1810", color2:"#1a0f0a", abv:14, iba:true, era:"クラシック",
   photo:"irish coffee cream coffee whiskey",
   flavor:{sweet:3,sour:0,bitter:3,strong:2,fresh:0,complex:3},
   ingredients:[["アイリッシュウイスキー","40ml"],["ホットコーヒー","100ml"],["砂糖（ブラウン）","2tsp"],["ホイップクリーム","適量"]],
   method:"温めたグラスにウイスキーと砂糖を入れ、熱いコーヒーを注ぎよく溶かす。冷たいクリームをスプーンの背でフロートさせる。",
   note:"1943年アイルランドのシャノン空港でジョー・シェリダンが、悪天候で引き返した旅行者を温めるために考案。"},
  {id:57, name:"Jungle Bird", nameJa:"ジャングル・バード", base:"ラム", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#ff9500", color2:"#e65100", abv:18, iba:false, era:"クラシック",
   photo:"jungle bird rum campari tropical",
   flavor:{sweet:3,sour:2,bitter:3,strong:2,fresh:2,complex:4},
   ingredients:[["ブラックストラップラム","45ml"],["カンパリ","22.5ml"],["フレッシュパイナップルジュース","45ml"],["フレッシュライムジュース","15ml"],["砂糖シロップ","15ml"]],
   method:"全材料をシェイクし、砕いた氷の入ったグラスに注ぐ。",
   note:"1978年クアラルンプールのヒルトンホテルで誕生。苦味とトロピカルの意外な融合が特徴。"},
  {id:58, name:"Bamboo", nameJa:"バンブー", base:"ワイン", taste:"辛口", glass:"カクテルグラス",
   color1:"#d4e8c0", color2:"#a5c78c", abv:14, iba:true, era:"クラシック",
   photo:"bamboo sherry vermouth cocktail",
   flavor:{sweet:1,sour:0,bitter:2,strong:2,fresh:2,complex:4},
   ingredients:[["ドライシェリー","45ml"],["ドライベルモット","45ml"],["オレンジビターズ","2dash"]],
   method:"ミキシンググラスに全材料と氷を入れてステアし、冷やしたカクテルグラスに注ぐ。レモンツイスト。",
   note:"1890年代横浜グランドホテルのチャールズ・ボルツが考案した世界初の日本発カクテル。"},
  {id:59, name:"Corpse Reviver #2", nameJa:"コープス・リバイバー #2", base:"ジン", taste:"酸味", glass:"カクテルグラス",
   color1:"#e8f8e8", color2:"#c8e6c9", abv:24, iba:true, era:"クラシック",
   photo:"corpse reviver gin absinthe cocktail",
   flavor:{sweet:1,sour:3,bitter:1,strong:3,fresh:3,complex:4},
   ingredients:[["ジン","22.5ml"],["コアントロー","22.5ml"],["リレ・ブラン","22.5ml"],["フレッシュレモンジュース","22.5ml"],["アブサン","rinse用"]],
   method:"アブサンでグラスをリンス。全材料をシェイクし、グラスに注ぐ。マラスキーノチェリーを添える。",
   note:"1930年「サボイ・カクテル・ブック」に掲載。「4杯以上飲むとホントに死ぬ」と書かれた二日酔い薬。"},
  {id:60, name:"Vieux Carré", nameJa:"ヴィユー・カレ", base:"ウイスキー", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:30, iba:false, era:"クラシック",
   photo:"vieux carre rye cognac cocktail",
   flavor:{sweet:2,sour:0,bitter:3,strong:5,fresh:0,complex:5},
   ingredients:[["ライウイスキー","22.5ml"],["コニャック","22.5ml"],["スイートベルモット","22.5ml"],["ベネディクティン","1tsp"],["アンゴスチュラ","2dash"],["ペイショーズ","2dash"]],
   method:"全材料を氷と共にミキシンググラスでステアし、グラスに注ぐ。レモンピールを添える。",
   note:"1930年代ニューオーリンズのモントレオーヌホテルで誕生。フレンチクォーター（旧市街）にちなむ。"},
  {id:61, name:"Aviation（IBA版）", nameJa:"アビエーション（IBA版）", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#7b68ee", color2:"#4b0082", abv:24, iba:true, era:"クラシック",
   photo:"aviation violet cocktail gin",
   flavor:{sweet:3,sour:2,bitter:0,strong:3,fresh:2,complex:4},
   ingredients:[["ジン","45ml"],["マラスキーノ","15ml"],["クレーム・ド・ヴィオレット","7.5ml"],["フレッシュレモンジュース","15ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"バイオレットが空の青紫色を表現。IBAオフィシャル入り。"},
  {id:62, name:"Clover Club（IBA）", nameJa:"クローバー・クラブ（IBA）", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#e8547a", color2:"#c2185b", abv:20, iba:true, era:"クラシック",
   photo:"clover club raspberry egg white cocktail",
   flavor:{sweet:3,sour:2,bitter:0,strong:2,fresh:2,complex:3},
   ingredients:[["ジン","45ml"],["フレッシュレモンジュース","15ml"],["ラズベリーシロップ","15ml"],["卵白","1個分"]],
   method:"ドライシェイク後、氷を加えて再度シェイク。冷やしたカクテルグラスに注ぐ。フレッシュラズベリーを飾る。",
   note:"IBAオフィシャル版。泡立ちのよい卵白が絹のような口当たりを生む。"},
  {id:63, name:"Rob Roy", nameJa:"ロブ・ロイ", base:"ウイスキー", taste:"甘口", glass:"カクテルグラス",
   color1:"#8b1a1a", color2:"#5d1111", abv:28, iba:false, era:"クラシック",
   photo:"rob roy scotch manhattan cocktail",
   flavor:{sweet:3,sour:0,bitter:2,strong:4,fresh:0,complex:3},
   ingredients:[["スコッチ","50ml"],["スイートベルモット","25ml"],["アンゴスチュラビターズ","2dash"]],
   method:"ミキシンググラスでステアし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"スコッチ版マンハッタン。スコットランドの英雄「ロバート・ロイ・マクグレガー」に捧げた1894年の作品。"},
  {id:64, name:"Stinger", nameJa:"スティンガー", base:"ブランデー", taste:"甘口", glass:"カクテルグラス",
   color1:"#e8f8e8", color2:"#a8d8a8", abv:30, iba:true, era:"クラシック",
   photo:"stinger cognac mint cocktail",
   flavor:{sweet:3,sour:0,bitter:0,strong:4,fresh:4,complex:2},
   ingredients:[["コニャック","50ml"],["クレーム・ド・メンテ（ホワイト）","20ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"アフターディナードリンクの定番。コニャックとミントの清涼感の意外な相性が魅力。"},
  {id:65, name:"Bijou", nameJa:"ビジュー", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#4caf50", color2:"#2e7d32", abv:30, iba:false, era:"クラシック",
   photo:"bijou cocktail chartreuse vermouth",
   flavor:{sweet:3,sour:0,bitter:1,strong:4,fresh:0,complex:5},
   ingredients:[["ジン","30ml"],["グリーン・シャルトリューズ","30ml"],["スイートベルモット","30ml"],["オレンジビターズ","1dash"]],
   method:"ミキシンググラスでステアし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"宝石を意味するフランス語。ダイヤモンド（ジン）、エメラルド（シャルトリューズ）、ルビー（ベルモット）の組み合わせ。"},
  {id:66, name:"Penicilin（スモーキー）", nameJa:"ペニシリン（スモーキー）", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#f5c842", color2:"#d4a017", abv:22, iba:false, era:"モダン",
   photo:"penicillin whisky ginger honey cocktail",
   flavor:{sweet:2,sour:3,bitter:1,strong:3,fresh:2,complex:5},
   ingredients:[["スコッチ","45ml"],["ラフロイグ（フロート）","7.5ml"],["フレッシュレモンジュース","22.5ml"],["蜂蜜生姜シロップ","22.5ml"]],
   method:"フロート以外をシェイクし、砕いた氷の入ったグラスへ。アイラをフロート。生姜片を飾る。",
   note:"スモーキーなアイラフロートがアクセント。複雑な風味と爽やかさの絶妙なバランス。"},
  {id:67, name:"Naked and Famous", nameJa:"ネイキッド・アンド・フェイマス", base:"テキーラ", taste:"苦味", glass:"カクテルグラス",
   color1:"#ffa726", color2:"#e65100", abv:24, iba:false, era:"モダン",
   photo:"naked famous mezcal aperol cocktail",
   flavor:{sweet:1,sour:3,bitter:3,strong:3,fresh:2,complex:4},
   ingredients:[["メスカル","22.5ml"],["アペロール","22.5ml"],["イエロー・シャルトリューズ","22.5ml"],["フレッシュライムジュース","22.5ml"]],
   method:"全材料を等量シェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"2011年NYのフィル・ウォードが考案。4素材等量のペーパー・プレーンの構造を踏襲するモダン傑作。"},
  {id:68, name:"Chartreuse Swizzle", nameJa:"シャルトリューズ・スウィズル", base:"リキュール", taste:"甘口", glass:"コリンズグラス",
   color1:"#4caf50", color2:"#2e7d32", abv:18, iba:false, era:"モダン",
   photo:"chartreuse swizzle green cocktail tropical",
   flavor:{sweet:3,sour:2,bitter:1,strong:3,fresh:4,complex:4},
   ingredients:[["グリーン・シャルトリューズ","45ml"],["ファレルナム","15ml"],["フレッシュパイナップルジュース","45ml"],["フレッシュライムジュース","15ml"]],
   method:"砕いた氷の入ったコリンズグラスに全材料を注ぎ、スウィズルスティックで回す。ミントを飾る。",
   note:"2003年サンフランシスコのマーコ・ディオニソスが考案。シャルトリューズ最良の引き立て役と称される。"},
  {id:69, name:"Between the Sheets", nameJa:"ビトウィーン・ザ・シーツ", base:"ブランデー", taste:"酸味", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:28, iba:true, era:"クラシック",
   photo:"between sheets brandy rum cocktail",
   flavor:{sweet:1,sour:3,bitter:0,strong:4,fresh:3,complex:3},
   ingredients:[["コニャック","30ml"],["ライトラム","30ml"],["コアントロー","30ml"],["フレッシュレモンジュース","20ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。レモンツイストを添える。",
   note:"サイドカーの変形版。禁酒法時代の1930年代に誕生したIBAオフィシャルカクテル。"},
  {id:70, name:"Sbagliato", nameJa:"ズバリャート", base:"ワイン", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#c0392b", color2:"#7b241c", abv:13, iba:false, era:"モダン",
   photo:"sbagliato campari prosecco cocktail",
   flavor:{sweet:2,sour:1,bitter:4,strong:2,fresh:3,complex:3},
   ingredients:[["カンパリ","30ml"],["スイートベルモット","30ml"],["プロセッコ","30ml"]],
   method:"氷の入ったグラスにすべてを注ぎ、軽くステアする。オレンジ添え。",
   note:"「失敗」を意味するイタリア語。バーテンダーの偶然の産物として今や世界的人気。"},
  {id:71, name:"Singapore Sling（オリジナル）", nameJa:"シンガポール・スリング（オリジナル）", base:"ジン", taste:"甘口", glass:"コリンズグラス",
   color1:"#e8547a", color2:"#9c1458", abv:15, iba:false, era:"クラシック",
   photo:"singapore sling pink tropical gin",
   flavor:{sweet:4,sour:2,bitter:1,strong:2,fresh:3,complex:5},
   ingredients:[["ジン","30ml"],["ヘアリング・チェリーリキュール","15ml"],["コアントロー","7.5ml"],["ドン・ベネディクティン","7.5ml"],["パイナップルジュース","120ml"],["ライムジュース","15ml"],["グレナデン","10ml"],["アンゴスチュラ","1dash"]],
   method:"全材料をシェイクし、氷の入ったコリンズグラスに注ぐ。パイナップルとチェリー。",
   note:"1915年シンガポール・ラッフルズホテルのロング・バーで誕生した伝説の一杯。"},
  {id:72, name:"Bramble（変形）", nameJa:"ジン・バジル・スマッシュ", base:"ジン", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#a8d8a8", color2:"#4caf50", abv:17, iba:false, era:"モダン",
   photo:"gin basil smash herb cocktail",
   flavor:{sweet:2,sour:3,bitter:1,strong:2,fresh:5,complex:3},
   ingredients:[["ジン","60ml"],["フレッシュバジル","1束"],["フレッシュレモンジュース","25ml"],["砂糖シロップ","15ml"]],
   method:"バジルをシェイカーでムドル。全材料をシェイクし、砕いた氷の入ったグラスに注ぐ。バジルを飾る。",
   note:"2008年ハンブルクのヨルク・マイヤーが考案。ハーブをメインに据えた画期的なモダン・クラシック。"},
  {id:73, name:"Amaretto Sour", nameJa:"アマレット・サワー", base:"リキュール", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#c97b3c", color2:"#8d4e14", abv:16, iba:false, era:"モダン",
   photo:"amaretto sour almond lemon cocktail",
   flavor:{sweet:4,sour:3,bitter:0,strong:2,fresh:2,complex:3},
   ingredients:[["アマレット","45ml"],["バーボン","22.5ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","7.5ml"],["卵白","1個分"]],
   method:"ドライシェイク後、氷を加えて再シェイク。グラスに注ぐ。チェリーとオレンジを飾る。",
   note:"バーテンダーのジェフ・モーゲンターラーが改良した現代版。バーボンが深みを加える。"},
  {id:74, name:"Mimosa", nameJa:"ミモザ", base:"ワイン", taste:"甘口", glass:"シャンパングラス",
   color1:"#ff9500", color2:"#f57c00", abv:7, iba:true, era:"クラシック",
   photo:"mimosa champagne orange juice brunch",
   flavor:{sweet:3,sour:1,bitter:0,strong:1,fresh:4,complex:1},
   ingredients:[["シャンパン","75ml"],["フレッシュオレンジジュース","75ml"]],
   method:"冷やしたシャンパングラスにOJを半分注ぎ、シャンパンをゆっくり満たす。",
   note:"1925年パリのリッツホテルで誕生（諸説あり）。ブランチの定番。ミモザの花の黄色から命名。"},
  {id:75, name:"Jungle Bird（IBAバージョン）", nameJa:"ジャングル・バード（IBA）", base:"ラム", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#ff9500", color2:"#bf360c", abv:18, iba:true, era:"クラシック",
   photo:"jungle bird rum pineapple campari tiki",
   flavor:{sweet:3,sour:2,bitter:3,strong:2,fresh:2,complex:4},
   ingredients:[["ジャマイカンダムラム","45ml"],["カンパリ","22.5ml"],["フレッシュパイナップルジュース","45ml"],["フレッシュライムジュース","15ml"],["砂糖シロップ","7.5ml"]],
   method:"全材料をシェイクし、砕いた氷の入ったグラスに注ぐ。パイナップルを飾る。",
   note:"IBAオフィシャル入り。苦味とトロピカルの絶妙な組み合わせで世界的に再評価されたカクテル。"},
  {id:76, name:"Porn Star Martini", nameJa:"ポルノスター・マティーニ", base:"ウォッカ", taste:"甘口", glass:"カクテルグラス",
   color1:"#ff9500", color2:"#e65100", abv:18, iba:false, era:"モダン",
   photo:"passion fruit martini cocktail tropical",
   flavor:{sweet:4,sour:2,bitter:0,strong:2,fresh:3,complex:2},
   ingredients:[["バニラウォッカ","50ml"],["パッションフルーツリキュール","50ml"],["フレッシュライムジュース","15ml"],["バニラシロップ","15ml"]],
   method:"全材料をシェイクし、グラスに注ぐ。パッションフルーツ半個を飾り、プロセッコを別グラスで添える。",
   note:"2002年ロンドンの「Townhouse」でダグラス・アンカーが考案。プロセッコを別グラスで出すスタイルが特徴。"},
  {id:77, name:"Sex on the Beach（IBA）", nameJa:"セックス・オン・ザ・ビーチ（IBA）", base:"ウォッカ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ff9500", color2:"#e8547a", abv:11, iba:true, era:"モダン",
   photo:"sex beach cocktail orange peach tropical",
   flavor:{sweet:4,sour:1,bitter:0,strong:1,fresh:3,complex:1},
   ingredients:[["ウォッカ","40ml"],["ピーチシュナップス","20ml"],["フレッシュオレンジジュース","40ml"],["クランベリージュース","40ml"]],
   method:"全材料を氷の入ったグラスに注ぎ、軽くステア。オレンジスライスを添える。",
   note:"IBAオフィシャル版。1980年代フロリダのリゾートバーから発祥した夏の定番。"},
  {id:78, name:"Clover Club（変形）", nameJa:"ジャスミン", base:"ジン", taste:"苦味", glass:"カクテルグラス",
   color1:"#e8547a", color2:"#ad1457", abv:24, iba:false, era:"モダン",
   photo:"jasmine gin campari cocktail pink",
   flavor:{sweet:1,sour:3,bitter:3,strong:3,fresh:3,complex:4},
   ingredients:[["ジン","37.5ml"],["カンパリ","22.5ml"],["コアントロー","7.5ml"],["フレッシュレモンジュース","22.5ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。レモンツイスト。",
   note:"1990年代サンフランシスコのポールのタランティーノが考案。苦味と酸味の美しいバランス。"},
  {id:79, name:"Bramble（クラシック）", nameJa:"スロー・ジン・フィズ", base:"リキュール", taste:"甘口", glass:"コリンズグラス",
   color1:"#e8547a", color2:"#ad1457", abv:10, iba:false, era:"クラシック",
   photo:"sloe gin fizz berry cocktail",
   flavor:{sweet:3,sour:2,bitter:0,strong:1,fresh:4,complex:2},
   ingredients:[["スロージン","45ml"],["フレッシュレモンジュース","22.5ml"],["砂糖シロップ","15ml"],["ソーダ水","60ml"]],
   method:"スロージン、レモン、シロップをシェイクし、氷の入ったグラスに注ぎソーダを加える。",
   note:"英国伝統のスロー（野生プラム）由来のリキュールを使ったリフレッシングなフィズ。"},
  {id:80, name:"Garibaldi", nameJa:"ガリバルディ", base:"リキュール", taste:"苦味", glass:"ハイボールグラス",
   color1:"#ff9500", color2:"#e65100", abv:8, iba:false, era:"モダン",
   photo:"garibaldi campari orange juice cocktail",
   flavor:{sweet:2,sour:1,bitter:4,strong:1,fresh:4,complex:2},
   ingredients:[["カンパリ","50ml"],["フルッフィーオレンジジュース（よく泡立てたもの）","150ml"]],
   method:"カンパリをグラスに注ぎ、よく泡立てたフレッシュオレンジジュースを注ぐ。",
   note:"「フルッフィー（fluffy）」に仕上げたOJが決め手。NYのミロ・ロドリゲスが2015年に復活させた。"},
  {id:81, name:"Bamboo（IBA）", nameJa:"バンブー（IBA）", base:"ワイン", taste:"辛口", glass:"カクテルグラス",
   color1:"#d4e8c0", color2:"#8bc34a", abv:14, iba:true, era:"クラシック",
   photo:"bamboo sherry vermouth low alcohol cocktail",
   flavor:{sweet:1,sour:0,bitter:2,strong:2,fresh:2,complex:4},
   ingredients:[["フィノシェリー","45ml"],["ドライベルモット","45ml"],["オレンジビターズ","2dash"],["アンゴスチュラ","1dash"]],
   method:"ミキシンググラスでよくステアし、冷やしたカクテルグラスに注ぐ。レモンツイスト。",
   note:"IBAオフィシャル認定を受けた日本発のカクテル。ローアルコールの先駆けとして近年再評価。"},
  {id:82, name:"Angel Face", nameJa:"エンジェル・フェイス", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:30, iba:true, era:"クラシック",
   photo:"angel face gin apricot calvados cocktail",
   flavor:{sweet:3,sour:0,bitter:0,strong:4,fresh:1,complex:3},
   ingredients:[["ジン","30ml"],["アプリコット・ブランデー","30ml"],["カルヴァドス","30ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"1930年「サボイ・カクテル・ブック」掲載。ハリー・クラドックによるIBAオフィシャルの名作。"},
  {id:83, name:"El Diablo", nameJa:"エル・ディアブロ", base:"テキーラ", taste:"辛口", glass:"コリンズグラス",
   color1:"#e8547a", color2:"#ad1457", abv:12, iba:true, era:"クラシック",
   photo:"el diablo tequila ginger beer cassis",
   flavor:{sweet:2,sour:2,bitter:0,strong:2,fresh:4,complex:3},
   ingredients:[["テキーラ（ブランコ）","45ml"],["クレーム・ド・カシス","15ml"],["フレッシュライムジュース","15ml"],["ジンジャービア","60ml"]],
   method:"氷の入ったグラスに全材料を注ぎ、軽くステア。ライムを添える。",
   note:"「悪魔」を意味するスペイン語。テキーラとカシスの意外な組み合わせが魅力のIBAオフィシャル。"},
  {id:84, name:"Tuxedo", nameJa:"タキシード", base:"ジン", taste:"辛口", glass:"カクテルグラス",
   color1:"#d4e8f0", color2:"#90caf9", abv:32, iba:false, era:"クラシック",
   photo:"tuxedo gin sherry vintage cocktail",
   flavor:{sweet:1,sour:0,bitter:2,strong:5,fresh:1,complex:5},
   ingredients:[["ジン","37.5ml"],["ドライシェリー","37.5ml"],["マラスキーノ","2.5ml"],["アニゼット","2.5ml"],["オレンジビターズ","3dash"]],
   method:"ミキシンググラスでよくステアし、冷やしたカクテルグラスに注ぐ。マラスキーノチェリーを添える。",
   note:"19世紀ニューヨークの紳士クラブ「タキシードパーク」にちなむ優雅なカクテル。"},
  {id:85, name:"Jungle Bird（モダン版）", nameJa:"ペーパー・プレーン", base:"ウイスキー", taste:"苦味", glass:"カクテルグラス",
   color1:"#f0a800", color2:"#e65100", abv:26, iba:false, era:"モダン",
   photo:"paper plane cocktail equal parts bourbon",
   flavor:{sweet:1,sour:3,bitter:3,strong:3,fresh:2,complex:4},
   ingredients:[["バーボン","22.5ml"],["アペロール","22.5ml"],["アメール・ピコン","22.5ml"],["フレッシュレモンジュース","22.5ml"]],
   method:"全材料を等量シェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"2008年NYのサム・ロスが考案。4素材等量の美しい均衡。M.I.Aの楽曲からネーミング。"},
  {id:86, name:"Adonis", nameJa:"アドニス", base:"ワイン", taste:"甘口", glass:"カクテルグラス",
   color1:"#c97b3c", color2:"#8d4e14", abv:14, iba:true, era:"クラシック",
   photo:"adonis sherry vermouth low alcohol",
   flavor:{sweet:2,sour:0,bitter:1,strong:1,fresh:1,complex:4},
   ingredients:[["フィノシェリー","45ml"],["スイートベルモット","22.5ml"],["オレンジビターズ","2dash"]],
   method:"ミキシンググラスでよくステアし、冷やしたカクテルグラスに注ぐ。オレンジツイスト。",
   note:"1884年ブロードウェイのミュージカル「アドニス」にちなむ。バンブーの姉妹カクテル。IBAオフィシャル。"},
  {id:87, name:"New York Sour（IBA）", nameJa:"ニューヨーク・サワー（IBA）", base:"ウイスキー", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#8b1a1a", color2:"#6d1414", abv:20, iba:true, era:"クラシック",
   photo:"new york sour red wine float whiskey",
   flavor:{sweet:2,sour:4,bitter:1,strong:3,fresh:3,complex:3},
   ingredients:[["バーボン","60ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["赤ワイン（フロート）","15ml"],["卵白","1個分（任意）"]],
   method:"バーボン、レモン、シロップ（卵白）をシェイクし、グラスに注ぐ。ワインをゆっくりフロート。",
   note:"IBAオフィシャル版。赤ワインのフロートがルビー色の層を作る視覚的にも美しいカクテル。"},
  {id:88, name:"Rusty Nail", nameJa:"ラスティ・ネイル", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#c97b3c", color2:"#8d4e14", abv:32, iba:false, era:"クラシック",
   photo:"rusty nail scotch drambuie cocktail",
   flavor:{sweet:3,sour:0,bitter:0,strong:4,fresh:0,complex:3},
   ingredients:[["スコッチ","45ml"],["ドランブイ","25ml"]],
   method:"氷の入ったオールドファッションドグラスに両材料を注ぎ、ゆっくりステアする。レモンツイストを添える。",
   note:"スコッチとスコッチ由来のハニー系リキュールの黄金組み合わせ。1960年代の「Rat Pack」が愛飲。"},
  {id:89, name:"Jungle Bird（アイランド）", nameJa:"ティ・パンチ", base:"ラム", taste:"辛口", glass:"オールドファッションドグラス",
   color1:"#e8d5a3", color2:"#c4a96d", abv:35, iba:false, era:"クラシック",
   photo:"ti punch martinique rum lime cocktail",
   flavor:{sweet:1,sour:2,bitter:0,strong:5,fresh:3,complex:2},
   ingredients:[["マルティニーク農業ラム（Rhum Agricole）","60ml"],["フレッシュライム","1/2個"],["サトウキビシロップ","10ml"]],
   method:"グラスにライムを搾り込み、シロップを加え、ラムを注いで軽くステア。氷は任意。",
   note:"カリブ海マルティニーク島の伝統的飲み方。「小さなパンチ」を意味するクレオール語。"},
  {id:90, name:"Midori Sour", nameJa:"ミドリ・サワー", base:"リキュール", taste:"甘口", glass:"ハイボールグラス",
   color1:"#7cb342", color2:"#33691e", abv:10, iba:false, era:"モダン",
   photo:"midori sour melon green cocktail",
   flavor:{sweet:4,sour:3,bitter:0,strong:1,fresh:3,complex:1},
   ingredients:[["ミドリ（メロンリキュール）","40ml"],["フレッシュレモンジュース","20ml"],["卵白","1個分"],["ソーダ水","適量"]],
   method:"ミドリ、レモン、卵白をシェイクし、氷の入ったグラスに注ぎソーダを加える。",
   note:"サントリーのミドリは1978年NY・マクソウェルズ・プラムで世界デビュー。日本生まれの国際的カクテル。"},
  {id:91, name:"Planter's Punch", nameJa:"プランターズ・パンチ", base:"ラム", taste:"甘口", glass:"コリンズグラス",
   color1:"#ff9500", color2:"#e65100", abv:13, iba:true, era:"クラシック",
   photo:"planters punch rum tropical fruit cocktail",
   flavor:{sweet:3,sour:3,bitter:1,strong:2,fresh:4,complex:3},
   ingredients:[["ダークラム","60ml"],["フレッシュライムジュース","30ml"],["砂糖シロップ","15ml"],["グレナデン","10ml"],["アンゴスチュラ","2dash"]],
   method:"全材料をシェイクし、氷の入ったコリンズグラスに注ぐ。フルーツを飾る。",
   note:"「1部サワー、2部甘、3部強、4部弱」の古いカクテルの韻文からレシピが伝わるジャマイカ生まれの傑作。"},
  {id:92, name:"Golden Dream", nameJa:"ゴールデン・ドリーム", base:"リキュール", taste:"甘口", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:18, iba:true, era:"クラシック",
   photo:"golden dream galliano orange cream cocktail",
   flavor:{sweet:4,sour:1,bitter:0,strong:2,fresh:2,complex:3},
   ingredients:[["ガリアーノ","20ml"],["コアントロー","20ml"],["フレッシュオレンジジュース","20ml"],["生クリーム","20ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"黄金色に輝くデザートカクテル。IBAオフィシャル。ガリアーノのハーブ香とクリームの甘さが融合。"},
  {id:93, name:"Sherry Cobbler", nameJa:"シェリー・コブラー", base:"ワイン", taste:"甘口", glass:"ゴブレット",
   color1:"#c97b3c", color2:"#8d4e14", abv:14, iba:false, era:"クラシック",
   photo:"sherry cobbler wine cocktail crushed ice",
   flavor:{sweet:3,sour:1,bitter:0,strong:2,fresh:3,complex:3},
   ingredients:[["アモンティリャードシェリー","90ml"],["砂糖","2tsp"],["オレンジスライス","1枚"]],
   method:"砕いた氷の入ったゴブレットに全材料を注ぎ、軽くステア。季節のフルーツで飾りストローで飲む。",
   note:"ストローを一般化させた19世紀最も人気のカクテル。アメリカンカルチャーの象徴として世界に広まった。"},
  {id:94, name:"Buck's Fizz", nameJa:"バックス・フィズ", base:"ワイン", taste:"甘口", glass:"シャンパングラス",
   color1:"#ff9500", color2:"#f57c00", abv:7, iba:false, era:"クラシック",
   photo:"bucks fizz champagne orange juice",
   flavor:{sweet:3,sour:1,bitter:0,strong:1,fresh:4,complex:1},
   ingredients:[["シャンパン","150ml"],["フレッシュオレンジジュース","75ml"]],
   method:"冷やしたシャンパングラスにOJを注ぎ、シャンパンを静かに満たす。",
   note:"ミモザの英国版。1921年ロンドン・バックス・クラブで誕生。ミモザより比率はシャンパン多め（2:1）。"},
  {id:95, name:"Pendennis Club Cocktail", nameJa:"ペンデニス・クラブ・カクテル", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:25, iba:false, era:"クラシック",
   photo:"pendennis club gin apricot cocktail",
   flavor:{sweet:3,sour:2,bitter:1,strong:3,fresh:2,complex:3},
   ingredients:[["ジン","45ml"],["アプリコットブランデー","22.5ml"],["フレッシュライムジュース","15ml"],["ペイショーズビターズ","2dash"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"1900年代ケンタッキー州ルイビルのペンデニス・クラブが発祥。オールド・ファッションドの発祥地とも言われる。"},
  {id:96, name:"Tommy's Margarita（IBA）", nameJa:"トミーズ・マルガリータ（IBA）", base:"テキーラ", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#e8f8e8", color2:"#66bb6a", abv:22, iba:true, era:"モダン",
   photo:"tommys margarita agave tequila lime",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:4,complex:3},
   ingredients:[["100%アガベテキーラ（ブランコ）","60ml"],["フレッシュライムジュース","30ml"],["アガベシロップ","15ml"]],
   method:"全材料をシェイクし、岩塩リムの砕いた氷入りグラスに注ぐ。",
   note:"IBAオフィシャル認定のモダン・クラシック。コアントロー不使用でテキーラの風味を純粋に引き出す。"},
  {id:97, name:"Clover Club 3", nameJa:"エル・プレジデンテ", base:"ラム", taste:"甘口", glass:"カクテルグラス",
   color1:"#f5c842", color2:"#d4a017", abv:28, iba:true, era:"クラシック",
   photo:"el presidente rum vermouth cocktail cuba",
   flavor:{sweet:3,sour:0,bitter:1,strong:4,fresh:1,complex:4},
   ingredients:[["ゴールドラム","60ml"],["スイートベルモット（またはドライ）","20ml"],["コアントロー","5ml"],["グレナデン","5ml"]],
   method:"全材料をミキシンググラスでステアし、冷やしたカクテルグラスに注ぐ。オレンジツイスト。",
   note:"1920年代キューバ生まれ。当時の大統領（プレジデンテ）にちなむ。ラムベースのマンハッタン。"},
  {id:98, name:"Satan's Whiskers", nameJa:"サタンズ・ウィスカーズ", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#ff9500", color2:"#e65100", abv:22, iba:false, era:"クラシック",
   photo:"satans whiskers gin vermouth orange cocktail",
   flavor:{sweet:2,sour:1,bitter:2,strong:3,fresh:2,complex:4},
   ingredients:[["ジン","22.5ml"],["スイートベルモット","22.5ml"],["ドライベルモット","22.5ml"],["ガリアーノ","15ml"],["フレッシュオレンジジュース","22.5ml"],["オレンジビターズ","1dash"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"1930年「サボイ・カクテル・ブック」掲載。「悪魔の口ひげ」という不吉な名をもつ美しいカクテル。"},
  {id:99, name:"Pink Gin", nameJa:"ピンク・ジン", base:"ジン", taste:"苦味", glass:"カクテルグラス",
   color1:"#ffb3ba", color2:"#ff6b6b", abv:36, iba:false, era:"クラシック",
   photo:"pink gin bitters cocktail",
   flavor:{sweet:0,sour:0,bitter:3,strong:5,fresh:0,complex:2},
   ingredients:[["ジン","60ml"],["アンゴスチュラビターズ","3dash"]],
   method:"グラスにビターズを入れコーティングし余分を捨てる。ジンを加えてステアする。",
   note:"19世紀英国海軍が船酔いに悩む航海者のために飲んだ記録あり。2素材の究極のシンプルさ。"},
  {id:100, name:"Jungle Bird 100", nameJa:"スプリング・フィーリング", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#b8e986", color2:"#7cb342", abv:24, iba:true, era:"クラシック",
   photo:"spring feeling gin lemon chartreuse cocktail",
   flavor:{sweet:2,sour:3,bitter:0,strong:3,fresh:4,complex:3},
   ingredients:[["ジン","45ml"],["グリーン・シャルトリューズ","15ml"],["フレッシュレモンジュース","15ml"]],
   method:"全材料をシェイクし、冷やしたカクテルグラスに注ぐ。",
   note:"1930年「サボイ・カクテル・ブック」掲載のハリー・クラドックによるIBAオフィシャル。春の芽吹きを表現。"},

  // ===== MD未登録分の追加 =====
  // ジン (G005, G012, G020)
  {id:101, name:"White Lady", nameJa:"ホワイト・レディ", base:"ジン", taste:"酸味", glass:"カクテルグラス",
   color1:"#f0ede8", color2:"#d8d0c0", abv:28, iba:true, era:"クラシック",
   flavor:{sweet:1,sour:3,bitter:0,strong:3,fresh:2,complex:2},
   ingredients:[["ジン","40ml"],["コアントロー","30ml"],["フレッシュレモンジュース","20ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"1919年ロンドンのデルモニコス・バーでハリー・マクエルホーン考案。絹のような滑らかな口当たりが特徴。"},
  {id:102, name:"Vesper", nameJa:"ベスパー", base:"ジン", taste:"辛口", glass:"カクテルグラス",
   color1:"#f5f0e0", color2:"#e0d5b0", abv:32, iba:true, era:"クラシック",
   flavor:{sweet:0,sour:0,bitter:1,strong:5,fresh:1,complex:3},
   ingredients:[["ジン","45ml"],["ウォッカ","15ml"],["リレ・ブラン","7.5ml"]],
   method:"シェイク後、冷やしたカクテルグラスに注ぐ。大きなレモンピールを飾る。",
   note:"イアン・フレミングの小説「カジノ・ロワイヤル」でジェームズ・ボンドが考案。ヒロインのベスパー・リンドに由来。"},
  {id:103, name:"Texas Fizz", nameJa:"南国ジン・サワー", base:"ジン", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ffcc80", color2:"#ef6c00", abv:14, iba:false, era:"クラシック",
   flavor:{sweet:3,sour:2,bitter:0,strong:2,fresh:3,complex:1},
   ingredients:[["ジン","45ml"],["フレッシュオレンジジュース","30ml"],["フレッシュレモンジュース","15ml"],["砂糖シロップ","10ml"],["ソーダ水","適量"]],
   method:"ジン、オレンジジュース、レモンジュース、シロップをシェイク。グラスに注ぎ、ソーダ水で満たす。オレンジスライスを飾る。",
   note:"テキサスの名を冠したロングドリンク。南国のオレンジとレモンの爽やかな組み合わせが特徴。"},

  // ウォッカ (V022, V024, V030, V035)
  {id:104, name:"Screwdriver", nameJa:"スクリュードライバー", base:"ウォッカ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ff9800", color2:"#f57c00", abv:11, iba:true, era:"クラシック",
   flavor:{sweet:3,sour:1,bitter:0,strong:1,fresh:3,complex:0},
   ingredients:[["ウォッカ","50ml"],["フレッシュオレンジジュース","100ml"]],
   method:"グラスに氷を入れ、ウォッカを注ぎオレンジジュースで満たす。軽くステアする。",
   note:"1940年代、中東で働くアメリカ人石油作業員がスクリュードライバーでかき混ぜたことが名前の由来。"},
  {id:105, name:"Salty Dog", nameJa:"ソルティ・ドッグ", base:"ウォッカ", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#ff8a65", color2:"#e64a19", abv:14, iba:true, era:"クラシック",
   flavor:{sweet:1,sour:3,bitter:0,strong:2,fresh:3,complex:1},
   ingredients:[["ウォッカ","45ml"],["グレープフルーツジュース","適量"]],
   method:"グラスのリムを塩でスノースタイルに。氷とウォッカを入れ、グレープフルーツジュースで満たす。",
   note:"元々はジンベースのドッグが原型。「ソルティ・ドッグ」は英国海軍の俗語で「老練な船乗り」の意。"},
  {id:106, name:"Kamikaze", nameJa:"カミカゼ", base:"ウォッカ", taste:"酸味", glass:"カクテルグラス",
   color1:"#f0f4c3", color2:"#c5e1a5", abv:26, iba:false, era:"クラシック",
   flavor:{sweet:1,sour:4,bitter:0,strong:3,fresh:3,complex:1},
   ingredients:[["ウォッカ","30ml"],["コアントロー","30ml"],["フレッシュライムジュース","30ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"第二次大戦後、日本に駐留した米軍が考案したとされる。コスモポリタンに似た構成でよりシャープな味わい。"},
  {id:107, name:"Appletini", nameJa:"アップルティーニ", base:"ウォッカ", taste:"甘口", glass:"カクテルグラス",
   color1:"#8bc34a", color2:"#558b2f", abv:20, iba:false, era:"モダン",
   flavor:{sweet:4,sour:2,bitter:0,strong:2,fresh:2,complex:0},
   ingredients:[["ウォッカ","40ml"],["アップルリキュール","20ml"],["フレッシュライムジュース","10ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。リンゴスライスを飾る。",
   note:"1990年代ニューヨーク生まれ。ドラマ「スクラブス」でのJ.Dキャラクターの愛飲品として世界的に有名。"},

  // ラム (R049)
  {id:108, name:"Caipirinha", nameJa:"カイピリーニャ", base:"ラム", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#f9f5e7", color2:"#c6e48b", abv:20, iba:true, era:"クラシック",
   flavor:{sweet:2,sour:4,bitter:0,strong:3,fresh:4,complex:1},
   ingredients:[["カシャーサ","60ml"],["ライム","半個（8分割）"],["砂糖","2tsp"]],
   method:"グラスにライムと砂糖を入れムドルして潰す。砕いた氷を満たし、カシャーサを注いでステアする。",
   note:"ブラジルの国民的カクテル。カシャーサはサトウキビを原料とするブラジル独自の蒸留酒。"},

  // ブランデー (B079, B084)
  {id:109, name:"French Connection", nameJa:"フレンチ・コネクション", base:"ブランデー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#8b5a2b", color2:"#6b4226", abv:32, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:0,bitter:1,strong:4,fresh:0,complex:2},
   ingredients:[["コニャック","35ml"],["アマレット","35ml"]],
   method:"ロックグラスに大きな氷を入れ、コニャックとアマレットを注いで軽くステアする。",
   note:"1971年の同名フランス映画を記念して考案。コニャック（フランス）とアマレット（イタリア）の融合。"},
  {id:110, name:"Brandy Crusta", nameJa:"ブランデー・クラスタ", base:"ブランデー", taste:"酸味", glass:"カクテルグラス",
   color1:"#c8a060", color2:"#a07040", abv:28, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:1,strong:3,fresh:1,complex:3},
   ingredients:[["コニャック","50ml"],["マラスキーノリキュール","10ml"],["コアントロー","10ml"],["フレッシュレモンジュース","20ml"],["アンゴスチュラビターズ","1dash"]],
   method:"グラスのリムを砂糖でスノースタイルに。長いレモンピールをグラス内側に巻き込む。全材料をステアしてグラスに注ぐ。",
   note:"1850年代ニューオーリンズ考案。砂糖のリムと大きなレモンピールが特徴の装飾的スタイルの元祖。"},

  // リキュール (L086, L087)
  {id:111, name:"Grasshopper", nameJa:"グラスホッパー", base:"リキュール", taste:"甘口", glass:"カクテルグラス",
   color1:"#66bb6a", color2:"#2e7d32", abv:15, iba:false, era:"クラシック",
   flavor:{sweet:5,sour:0,bitter:0,strong:1,fresh:3,complex:1},
   ingredients:[["グリーン・ペパーミントリキュール","30ml"],["ホワイト・カカオリキュール","30ml"],["生クリーム","30ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"1950年代ニューオーリンズのチュレーヌ・レストランで誕生。チョコミントのデザートカクテル。名はその鮮やかな緑色から。"},
  {id:112, name:"Cassis Soda", nameJa:"カシス・ソーダ", base:"リキュール", taste:"甘口", glass:"ハイボールグラス",
   color1:"#6a1b9a", color2:"#4a148c", abv:7, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:1,bitter:0,strong:0,fresh:2,complex:0},
   ingredients:[["クレーム・ド・カシス","45ml"],["ソーダ水","適量"]],
   method:"グラスに氷を入れカシスを注ぐ。ソーダ水で満たし軽くステアする。レモンスライスを添える。",
   note:"クレーム・ド・カシスはブラックカラントのリキュール。日本で最も普及したリキュールカクテルの一つ。"},

  // ワイン/ビール (W095)
  {id:113, name:"Shandy Gaff", nameJa:"シャンディ・ガフ", base:"ワイン", taste:"甘口", glass:"ハイボールグラス",
   color1:"#f9a825", color2:"#f57f17", abv:3, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:0,bitter:1,strong:0,fresh:3,complex:0},
   ingredients:[["ビール","適量（1/2）"],["ジンジャーエール","適量（1/2）"]],
   method:"冷えたグラスにビールを半分注ぎ、ジンジャーエールで満たす。",
   note:"19世紀英国発祥のビールカクテル。「シャンディ」はビールと炭酸飲料を混ぜたものの英国英語。"},

  // ノンアルコール (N096-N100)
  {id:114, name:"Cinderella", nameJa:"シンデレラ", base:"ノンアルコール", taste:"甘口", glass:"カクテルグラス",
   color1:"#ff9800", color2:"#ffa726", abv:0, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:2,bitter:0,strong:0,fresh:4,complex:1},
   ingredients:[["パイナップルジュース","30ml"],["オレンジジュース","30ml"],["フレッシュレモンジュース","30ml"],["グレナデンシロップ","10ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"シンデレラのように華やかなモクテル。フルーツジュースの組み合わせで彩り豊かな一杯。"},
  {id:115, name:"Shirley Temple", nameJa:"シャーリー・テンプル", base:"ノンアルコール", taste:"甘口", glass:"ハイボールグラス",
   color1:"#e91e63", color2:"#c2185b", abv:0, iba:false, era:"クラシック",
   flavor:{sweet:5,sour:0,bitter:0,strong:0,fresh:2,complex:0},
   ingredients:[["ジンジャーエール","適量"],["グレナデンシロップ","15ml"]],
   method:"グラスに氷を入れ、グレナデンを注ぐ。ジンジャーエールで満たし、マラスキーノチェリーを飾る。",
   note:"1930年代ハリウッドの伝説的子役シャーリー・テンプルのために考案。最も有名なモクテルの一つ。"},
  {id:116, name:"Saratoga Cooler", nameJa:"サラトガ・クーラー", base:"ノンアルコール", taste:"酸味", glass:"ハイボールグラス",
   color1:"#e8f5e9", color2:"#a5d6a7", abv:0, iba:false, era:"クラシック",
   flavor:{sweet:1,sour:3,bitter:0,strong:0,fresh:5,complex:0},
   ingredients:[["ジンジャーエール","適量"],["フレッシュライムジュース","30ml"]],
   method:"グラスに氷を入れ、ライムジュースを注ぐ。ジンジャーエールで満たしてステアし、ライムを飾る。",
   note:"ニューヨーク州サラトガスプリングスの高級保養地にちなんだ上品なノンアルコールドリンク。"},
  {id:117, name:"Virgin Mojito", nameJa:"バージン・モヒート", base:"ノンアルコール", taste:"酸味", glass:"ハイボールグラス",
   color1:"#e8f5e9", color2:"#81c784", abv:0, iba:false, era:"モダン",
   flavor:{sweet:2,sour:2,bitter:0,strong:0,fresh:5,complex:1},
   ingredients:[["ミントの葉","10枚"],["フレッシュライムジュース","30ml"],["砂糖シロップ","15ml"],["ソーダ水","適量"]],
   method:"ミントとライムジュース、シロップをグラスでムドルする。クラッシュアイスを加え、ソーダ水で満たす。",
   note:"モヒートのノンアルコール版。健康志向の高まりとともに世界中のバーで定番モクテルに。"},
  {id:118, name:"Pussyfoot", nameJa:"プッシーフット", base:"ノンアルコール", taste:"甘口", glass:"カクテルグラス",
   color1:"#ffca28", color2:"#ff8f00", abv:0, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:2,bitter:0,strong:0,fresh:3,complex:1},
   ingredients:[["オレンジジュース","30ml"],["フレッシュレモンジュース","30ml"],["フレッシュライムジュース","30ml"],["グレナデンシロップ","10ml"],["卵黄","1個"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"禁酒運動家ウィリアム・「プッシーフット」・ジョンソンの名を冠したモクテル。卵黄が濃厚なコクを生む。"},

  // ===== MDファイル最新化による追加分 =====
  // ジン (G006, G013, G014)
  {id:119, name:"Gin Fizz", nameJa:"ジン・フィズ", base:"ジン", taste:"酸味", glass:"ハイボールグラス",
   color1:"#e8f4fd", color2:"#b3d9f2", abv:14, iba:true, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:2,fresh:4,complex:1},
   ingredients:[["ジン","45ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["ソーダ水","適量"]],
   method:"ジン、レモン、シロップをシェイク。グラスに注ぎ、ソーダ水で満たす。レモンスライスを飾る。",
   note:"「フィズ」は炭酸が弾ける擬音に由来。トム・コリンズと構成が似るが短いタンブラーで提供するのが特徴。"},
  {id:120, name:"Gin Rickey", nameJa:"ジン・リッキー", base:"ジン", taste:"辛口", glass:"ハイボールグラス",
   color1:"#e8f5e9", color2:"#a5d6a7", abv:12, iba:false, era:"クラシック",
   flavor:{sweet:0,sour:2,bitter:0,strong:2,fresh:5,complex:0},
   ingredients:[["ジン","45ml"],["フレッシュライムジュース","15ml"],["ソーダ水","適量"]],
   method:"グラスに氷を入れ、ライムを搾って皮ごと入れる。ジンを注ぎ、ソーダ水で満たす。",
   note:"1883年ワシントンDCで考案。砂糖を使わないのが特徴で、ジンの風味をそのまま楽しむスタイル。"},
  {id:121, name:"Pink Lady", nameJa:"ピンク・レディ", base:"ジン", taste:"甘口", glass:"カクテルグラス",
   color1:"#f8bbd9", color2:"#f06292", abv:22, iba:false, era:"クラシック",
   flavor:{sweet:3,sour:1,bitter:0,strong:3,fresh:1,complex:2},
   ingredients:[["ジン","45ml"],["グレナデンシロップ","15ml"],["卵白","1個"]],
   method:"全材料をドライシェイク後、氷を加えて再シェイク。冷やしたカクテルグラスに注ぐ。",
   note:"1912年のブロードウェイ舞台「ピンク・レディ」の主演女優を祝うために考案されたとされる。"},

  // ウォッカ (V029, V032, V034)
  {id:122, name:"Sea Breeze", nameJa:"シー・ブリーズ", base:"ウォッカ", taste:"酸味", glass:"ハイボールグラス",
   color1:"#e91e63", color2:"#c62828", abv:11, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:1,fresh:4,complex:0},
   ingredients:[["ウォッカ","40ml"],["クランベリージュース","100ml"],["グレープフルーツジュース","30ml"]],
   method:"グラスに氷を入れ、ウォッカ、クランベリー、グレープフルーツジュースを注ぎ軽くステアする。",
   note:"1980年代を代表するビーチリゾートカクテル。鮮やかな赤とフルーティーな味わいが特徴。"},
  {id:123, name:"Balalaika", nameJa:"バラライカ", base:"ウォッカ", taste:"酸味", glass:"カクテルグラス",
   color1:"#f5f0e8", color2:"#e0d5b0", abv:26, iba:false, era:"クラシック",
   flavor:{sweet:1,sour:3,bitter:0,strong:3,fresh:2,complex:1},
   ingredients:[["ウォッカ","30ml"],["コアントロー","30ml"],["フレッシュレモンジュース","30ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"ロシアの弦楽器バラライカが名の由来。サイドカーのブランデーをウォッカに替えた変形版。"},
  {id:124, name:"Lemon Drop", nameJa:"レモン・ドロップ", base:"ウォッカ", taste:"酸味", glass:"カクテルグラス",
   color1:"#fff9c4", color2:"#ffd54f", abv:22, iba:false, era:"モダン",
   flavor:{sweet:3,sour:3,bitter:0,strong:2,fresh:3,complex:0},
   ingredients:[["ウォッカ","30ml"],["コアントロー","15ml"],["フレッシュレモンジュース","15ml"]],
   method:"グラスのリムを砂糖でスノースタイルに。全材料をシェイクして注ぐ。レモンスライスを飾る。",
   note:"1970年代サンフランシスコで誕生。レモン飴のような親しみやすい甘酸っぱい味わい。"},

  // ラム (R041-R043, R045)
  {id:125, name:"X.Y.Z.", nameJa:"エックス・ワイ・ズィー", base:"ラム", taste:"酸味", glass:"カクテルグラス",
   color1:"#fff8e1", color2:"#ffe082", abv:26, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:3,fresh:2,complex:2},
   ingredients:[["ホワイトラム","30ml"],["ホワイトキュラソー","15ml"],["フレッシュレモンジュース","15ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"「これ以上はない」「終わり」を意味するXYZ。サイドカーのブランデーをラムに替えた変形版。"},
  {id:126, name:"Boston Cooler", nameJa:"ボストン・クーラー", base:"ラム", taste:"酸味", glass:"ハイボールグラス",
   color1:"#f5f5dc", color2:"#ddd8b0", abv:12, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:1,fresh:4,complex:1},
   ingredients:[["ラム","45ml"],["フレッシュレモンジュース","30ml"],["砂糖シロップ","15ml"],["ジンジャーエール","適量"]],
   method:"ラム、レモン、シロップをシェイク。グラスに注ぎ、ジンジャーエールで満たす。",
   note:"アメリカの避暑地ボストンの名を冠したロングドリンク。ジンジャーのスパイスが夏に爽快。"},
  {id:127, name:"Mary Pickford", nameJa:"メアリー・ピックフォード", base:"ラム", taste:"甘口", glass:"カクテルグラス",
   color1:"#ffc1cc", color2:"#ff7096", abv:22, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:1,bitter:0,strong:2,fresh:2,complex:1},
   ingredients:[["ホワイトラム","45ml"],["パイナップルジュース","45ml"],["グレナデンシロップ","10ml"],["マラスキーノリキュール","5ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"1920年代の無声映画の女王メアリー・ピックフォードがキューバ訪問の際に献呈されたカクテル。"},
  {id:128, name:"Scorpion", nameJa:"スコーピオン", base:"ラム", taste:"甘口", glass:"ゴブレット",
   color1:"#ff9800", color2:"#e65100", abv:22, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:2,bitter:0,strong:3,fresh:2,complex:2},
   ingredients:[["ラム","45ml"],["ブランデー","15ml"],["オレンジジュース","60ml"],["フレッシュレモンジュース","30ml"],["オルジェットシロップ","15ml"]],
   method:"全材料をシェイク。氷を入れたゴブレットに注ぐ。ミントを飾る。",
   note:"ポリネシア系ティキカクテルの一つ。サソリの毒のような後から回る魔力的な酔いが特徴。"},

  // テキーラ (T053, T054, T058, T059, T060)
  {id:129, name:"Matador", nameJa:"マタドール", base:"テキーラ", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#fff9c4", color2:"#ffd54f", abv:20, iba:false, era:"クラシック",
   flavor:{sweet:3,sour:2,bitter:0,strong:2,fresh:3,complex:1},
   ingredients:[["テキーラ","30ml"],["パイナップルジュース","60ml"],["フレッシュライムジュース","15ml"]],
   method:"全材料をシェイク。氷を入れたロックグラスに注ぐ。ライムを飾る。",
   note:"スペイン語で「闘牛士」の意。パイナップルの甘さがテキーラの風味を引き立てる夏向けカクテル。"},
  {id:130, name:"Mockingbird", nameJa:"モッキンバード", base:"テキーラ", taste:"酸味", glass:"カクテルグラス",
   color1:"#c8e6c9", color2:"#66bb6a", abv:26, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:2,bitter:0,strong:3,fresh:5,complex:1},
   ingredients:[["テキーラ","45ml"],["グリーン・ペパーミントリキュール","15ml"],["フレッシュライムジュース","15ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"「モノマネ鳥」の名を冠した爽快なカクテル。テキーラとミントの意外な組み合わせが清涼感を生む。"},
  {id:131, name:"Ambassador", nameJa:"アンバサダー", base:"テキーラ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#ff9800", color2:"#f57c00", abv:12, iba:false, era:"クラシック",
   flavor:{sweet:3,sour:1,bitter:0,strong:1,fresh:3,complex:1},
   ingredients:[["テキーラ","45ml"],["オレンジジュース","適量"],["砂糖シロップ","10ml"]],
   method:"グラスに氷を入れテキーラを注ぐ。砂糖シロップを加え、オレンジジュースで満たし軽くステアする。",
   note:"「大使」を意味するスペイン語。社交の場にふさわしい上品さとテキーラの風味が特徴。"},
  {id:132, name:"Sloe Tequila", nameJa:"スロー・テキーラ", base:"テキーラ", taste:"甘口", glass:"ハイボールグラス",
   color1:"#880e4f", color2:"#c62828", abv:14, iba:false, era:"クラシック",
   flavor:{sweet:3,sour:2,bitter:1,strong:2,fresh:1,complex:2},
   ingredients:[["テキーラ","45ml"],["スロー・ジン","30ml"],["フレッシュレモンジュース","15ml"]],
   method:"グラスに氷を入れ全材料を注ぎ、軽くステアする。レモンを飾る。",
   note:"テキーラとスモモ（スロー）リキュールの意外な組み合わせ。秋の深みある色彩と味わいが特徴。"},
  {id:133, name:"Picador", nameJa:"ピカドール", base:"テキーラ", taste:"酸味", glass:"カクテルグラス",
   color1:"#f5f5f5", color2:"#e0e0e0", abv:28, iba:false, era:"クラシック",
   flavor:{sweet:1,sour:3,bitter:0,strong:3,fresh:3,complex:1},
   ingredients:[["テキーラ","30ml"],["ホワイトキュラソー","30ml"],["フレッシュライムジュース","15ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"闘牛場の馬上槍士「ピカドール」の名を冠す。マルガリータの原型ともされるシャープな辛口。"},

  // ウイスキー (W066, W067, W075)
  {id:134, name:"Godfather", nameJa:"ゴッドファーザー", base:"ウイスキー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#8b5a2b", color2:"#5d3a1a", abv:32, iba:false, era:"クラシック",
   flavor:{sweet:4,sour:0,bitter:1,strong:4,fresh:0,complex:2},
   ingredients:[["スコッチウイスキー","45ml"],["アマレット","25ml"]],
   method:"ロックグラスに大きな氷を入れ、スコッチとアマレットを注いで軽くステアする。",
   note:"1972年の映画「ゴッドファーザー」公開を記念して考案。スコッチの力強さとアーモンドの甘さの絶妙な融合。"},
  {id:135, name:"New York", nameJa:"ニューヨーク", base:"ウイスキー", taste:"酸味", glass:"カクテルグラス",
   color1:"#c0392b", color2:"#e74c3c", abv:24, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:3,fresh:1,complex:2},
   ingredients:[["ウイスキー","45ml"],["フレッシュライムジュース","20ml"],["グレナデンシロップ","10ml"],["パウダーシュガー","1tsp"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。オレンジスライスを飾る。",
   note:"都会的でフルーティーなウイスキーカクテル。グレナデンの赤とライムの酸味が大都市の夕焼けを連想させる。"},
  {id:136, name:"Blood and Sand", nameJa:"ブラッド・アンド・サンド", base:"ウイスキー", taste:"甘口", glass:"カクテルグラス",
   color1:"#8b1a1a", color2:"#c0392b", abv:22, iba:true, era:"クラシック",
   flavor:{sweet:3,sour:1,bitter:1,strong:2,fresh:0,complex:3},
   ingredients:[["スコッチウイスキー","22.5ml"],["チェリーブランデー","22.5ml"],["スイートベルモット","22.5ml"],["フレッシュオレンジジュース","22.5ml"]],
   method:"全材料を均等量でシェイク。冷やしたカクテルグラスに注ぐ。オレンジスライスを飾る。",
   note:"1922年の闘牛映画「血と砂」からの命名。スコッチ・チェリー・ベルモット・オレンジの複雑な和音。"},

  // ブランデー (B080-B083, B085)
  {id:137, name:"Nikolaschka", nameJa:"ニコラシカ", base:"ブランデー", taste:"甘口", glass:"オールドファッションドグラス",
   color1:"#8b5a2b", color2:"#c8a060", abv:28, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:2,bitter:1,strong:4,fresh:0,complex:3},
   ingredients:[["ブランデー","45ml"],["レモンスライス","1枚"],["グラニュー糖","1tsp"],["インスタントコーヒー","少量"]],
   method:"小グラスにブランデーを注ぐ。レモンスライスの上に砂糖とコーヒーをのせてグラスに置く。レモンを口に含んでから飲む。",
   note:"ドイツ・ハンブルクで考案された独特の飲み方のカクテル。口の中で素材を混ぜる体験型ドリンク。"},
  {id:138, name:"Brandy Sour", nameJa:"ブランデー・サワー", base:"ブランデー", taste:"酸味", glass:"オールドファッションドグラス",
   color1:"#c8a060", color2:"#a07040", abv:22, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:3,bitter:0,strong:3,fresh:2,complex:2},
   ingredients:[["ブランデー","45ml"],["フレッシュレモンジュース","20ml"],["砂糖シロップ","15ml"]],
   method:"全材料をシェイク。氷を入れたロックグラスに注ぐ。オレンジとチェリーを飾る。",
   note:"ブランデーの気品をレモンの爽やかさで引き立てた古典的サワースタイル。飲みやすい定番の一杯。"},
  {id:139, name:"Porto Flip", nameJa:"ポルト・フリップ", base:"ブランデー", taste:"甘口", glass:"カクテルグラス",
   color1:"#7b1010", color2:"#5a0000", abv:18, iba:true, era:"クラシック",
   flavor:{sweet:4,sour:0,bitter:1,strong:2,fresh:0,complex:3},
   ingredients:[["ブランデー","15ml"],["ポートワイン","45ml"],["卵黄","1個"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。ナツメグを振りかける。",
   note:"19世紀の栄養補給飲料「フリップ」の系譜。ポルトガルのポートワインとブランデーの贅沢な組み合わせ。"},
  {id:140, name:"Horse's Neck", nameJa:"ホースズ・ネック", base:"ブランデー", taste:"甘口", glass:"ハイボールグラス",
   color1:"#f5f5dc", color2:"#d4c8a0", abv:10, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:1,bitter:0,strong:2,fresh:3,complex:1},
   ingredients:[["ブランデー","45ml"],["ジンジャーエール","適量"],["アンゴスチュラビターズ","1dash"]],
   method:"グラスに長いレモンの皮をらせん状に入れる。氷とブランデーを注ぎ、ジンジャーエールで満たす。",
   note:"らせん状のレモンの皮が馬の首のように見えることから命名。装飾性と飲みやすさを兼ね備えた一杯。"},
  {id:141, name:"B&B", nameJa:"ビー・アンド・ビー", base:"ブランデー", taste:"苦味", glass:"オールドファッションドグラス",
   color1:"#8b5a2b", color2:"#5d3a1a", abv:35, iba:false, era:"クラシック",
   flavor:{sweet:2,sour:0,bitter:3,strong:5,fresh:0,complex:4},
   ingredients:[["コニャック","30ml"],["ベネディクティン","30ml"]],
   method:"リキュールグラスにコニャックを注ぎ、スプーンの背でゆっくりベネディクティンを浮かべる。",
   note:"フランスのベネディクト会修道士が製法を守り続ける薬草系リキュールとコニャックの組み合わせ。"},

  // リキュール (L088-L090)
  {id:142, name:"Spumoni", nameJa:"スプモーニ", base:"リキュール", taste:"苦味", glass:"ハイボールグラス",
   color1:"#ff7043", color2:"#e64a19", abv:8, iba:false, era:"モダン",
   flavor:{sweet:2,sour:2,bitter:3,strong:1,fresh:3,complex:1},
   ingredients:[["カンパリ","30ml"],["グレープフルーツジュース","90ml"],["トニックウォーター","適量"]],
   method:"グラスに氷を入れカンパリを注ぐ。グレープフルーツジュースとトニックウォーターで満たし軽くステアする。",
   note:"イタリア語で「泡立つ」を意味する。アペロールスプリッツと並ぶイタリア系低アルコールカクテル。"},
  {id:143, name:"China Blue", nameJa:"チャイナ・ブルー", base:"リキュール", taste:"甘口", glass:"ハイボールグラス",
   color1:"#00bcd4", color2:"#006064", abv:8, iba:false, era:"モダン",
   flavor:{sweet:3,sour:2,bitter:0,strong:1,fresh:4,complex:1},
   ingredients:[["ライチリキュール","30ml"],["ブルーキュラソー","15ml"],["グレープフルーツジュース","適量"]],
   method:"グラスに氷を入れ、ライチリキュール、ブルーキュラソーを注ぐ。グレープフルーツジュースで満たす。",
   note:"日本で生まれた世界的ヒット作。鮮やかなターコイズブルーとライチの甘い香りが南国を連想させる。"},
  {id:144, name:"Golden Cadillac", nameJa:"ゴールデン・キャデラック", base:"リキュール", taste:"甘口", glass:"カクテルグラス",
   color1:"#ffd700", color2:"#ffb300", abv:15, iba:false, era:"クラシック",
   flavor:{sweet:5,sour:0,bitter:0,strong:1,fresh:0,complex:2},
   ingredients:[["ガリアーノ","30ml"],["ホワイト・カカオリキュール","30ml"],["生クリーム","30ml"]],
   method:"全材料をシェイク。冷やしたカクテルグラスに注ぐ。",
   note:"1950年代アメリカの繁栄を象徴するキャデラック（高級車）にちなんだ黄金色のデザートカクテル。"},

  // ワイン (W094 = シャンパン・カクテル)
  {id:145, name:"Champagne Cocktail", nameJa:"シャンパン・カクテル", base:"ワイン", taste:"甘口", glass:"シャンパングラス",
   color1:"#f5f0d0", color2:"#e8d88a", abv:12, iba:true, era:"クラシック",
   flavor:{sweet:3,sour:1,bitter:1,strong:1,fresh:3,complex:2},
   ingredients:[["シャンパン","適量"],["角砂糖","1個"],["アンゴスチュラビターズ","2dash"],["コニャック","10ml"]],
   method:"角砂糖にビターズを染み込ませフルートグラスに入れる。コニャックを注ぎ、冷えたシャンパンで満たす。",
   note:"映画「カサブランカ」（1942年）のシーンで世界的に有名になった古典的シャンパンカクテル。"},
];
